---
title: "LAI_Establishment_Weibull"
output: pdf_document
date: "2026-01-23"
---

```{r}
library(tidyverse)
library(rFIA)
library(nls2)
library(minpack.lm)
library(sf)
library(data.table)
library(readxl)
gc()
```



```{r}
# This script is adapted from Samuel Flake's work which can be found at https://github.com/LANDIS-II-Foundation/Project-Isle-Royale-2021/blob/fbbf6e3eb1bf1082dc37870119213f6725346e5f/Parameterization/lai_establishment_table_weibull_v2.R

fit_weibull <- function(dat, lower = c(-Inf, -Inf, 0, 0), upper = c(Inf, Inf, Inf, 10), use_c_d = "both") {
  
  #you might have to play with these starting values
  pars <- expand.grid(a=seq(0.1,10, len=50), #shape
                      b=seq(0.1, 20, len=10), #scale
                      c = 0, #threshold parameter; this sets the "floor" for the curve,
                      # the y-intercept for shape parameter > 1
                      # or asymptote for low values of shape parameters
                      d=seq(0.1, 20, len = 20) #removed d parameter, which scales everything vertically
                      #it does allow better fit but harder to converge
  )
  
  
  # a floor could be set by replacing c with a constant, rather than 
  # estimating it, though this could cause issues with convergence.
  # first round to get approximate starting values
  if(use_c_d == "both") formula <- prop_present ~ (((a/b) * ((lai/b)^(a-1)) * exp(- (lai/b)^a)) + c) * d
  if(use_c_d == "c"){
    formula <- prop_present ~ (((a/b) * ((lai/b)^(a-1)) * exp(- (lai/b)^a)) + c)
    pars <- pars[,c(1:3)]
    lower = lower[c(1:3)]
    upper = upper[c(1:3)]
  } 
  if(use_c_d == "d") {
    formula <- prop_present ~ (((a/b) * ((lai/b)^(a-1)) * exp(- (lai/b)^a))) * d
    pars <- pars[,c(1,2,4)]
    lower = lower[c(1,2,4)]
    upper = upper[c(1,2,4)]
  }
  if(use_c_d == "neither"){
    formula <- prop_present ~ (((a/b) * ((lai/b)^(a-1)) * exp(- (lai/b)^a)))
    pars <- pars[,c(1,2)]
    lower = lower[c(1,2)]
    upper = upper[c(1,2)]
    }
  
  res <- nls2(formula, 
              data=dat,
              start=pars, 
              algorithm='brute-force',
              upper = upper,
              lower = lower,
              weights = dat$n_plots_bin)
  
  #get better estimates using minpack
  res1 <- nlsLM(formula, 
                data=dat,
                start=as.list(coef(res)),
                upper = upper,
                lower = lower,
                weights = dat$n_plots_bin)
  
  #sometimes c will be negative, which would allow seedlings to sometimes be negative.
  #If that happens, refit the model with c = 0
  if(use_c_d %in% c("both", "c") & coef(res1)[3] < 0) {
    res1 <- nlsLM(prop_present ~ ((a/b) * ((lai/b)^(a-1)) * exp(- (lai/b)^a)),
                  data=dat,
                  start=as.list(coef(res)[c(1,2)]))
  }
  
  
  return(res1)
}

options(scipen = 999)


# Let us begin by wrangling the data. I will be using MN, WI and MI data
directory <- "D:/Minnesota/TreeMap/States/"
trees <- list.files(directory, pattern = "^(MN|WI|MI)_TREE\\.csv$", full.names = TRUE) %>% lapply(fread) %>% bind_rows()
plot <- list.files(directory, pattern = "^(MN|WI|MI)_PLOT\\.csv$", full.names = TRUE) %>% lapply(fread) %>% bind_rows()
cond <- list.files(directory, pattern = "^(MN|WI|MI)_COND\\.csv$", full.names = TRUE) %>% lapply(fread) %>% bind_rows()
seedlings <- list.files(directory, pattern = "^(MN|WI|MI)_SEEDLING\\.csv$", full.names = TRUE) %>% lapply(fread) %>% bind_rows()
sitetrees <- list.files(directory, pattern = "^(MN|WI|MI)_SITETREE\\.csv$", full.names = TRUE) %>% lapply(fread) %>% bind_rows()

gc()

# Now I have to filter plots that are of use. Not all plots are in forested condition
# some have been rcently treated etc. and we need to filter them out
condToUse <- cond %>%
  filter(!(DSTRBCD1 %in% c(30, 31, 32, 46, 53, 54, 80)),
         !(DSTRBCD2 %in% c(30, 31, 32, 46, 53, 54, 80)),
         !(DSTRBCD3 %in% c(30, 31, 32, 46, 53, 54, 80)),
         TRTCD1 == 0 | is.na(TRTCD1),
         TRTCD3 == 0 | is.na(TRTCD2),
         TRTCD1 == 0 | is.na(TRTCD3)) %>%
  mutate(IS_FOREST = ifelse(FORTYPCD %in% (c(1:998)), 1, 0)) %>%
  group_by(PLT_CN) %>%
  summarise(totalCond = sum(CONDPROP_UNADJ),
            natural = sum(STDORGCD, na.rm = TRUE),
            treatment = sum(TRTCD1, na.rm = TRUE),
            propForest = sum(CONDPROP_UNADJ * IS_FOREST)) %>%
  filter(totalCond > 0.95,
         propForest > 0.95)

plotsToUse <- plot %>%
  filter(PLOT_STATUS_CD == 1) %>%
  left_join(condToUse, by = c("CN" = "PLT_CN")) %>%
  dplyr::select(CN, propForest)



#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
# func_table <- read.csv("./Models/LANDIS inputs/NECN files/NECN_Functional_Table_inv_moisture.csv")
# sp_table <- read.csv("./Models/LANDIS inputs/NECN files/NECN_Spp_Table_inv_necn7.csv") %>%
#   left_join(func_table, by = "FunctionalGroupIndex") 
# 
# 
# #we need to assign each species group a value for KLAI and MaximumLAI
# #this needs to be revised for new LANDIS projects
# spgrp_lai <- data.frame(SPGRPCD = unique(trees$SPGRPCD),
#                         FunctionalGroupIndex = numeric(length(unique(trees$SPGRPCD)))) %>%
#   arrange(SPGRPCD) %>%
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(5,4, 3, 2), 1, FunctionalGroupIndex))%>% #jack and red pine
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(6), 2, FunctionalGroupIndex))%>%   #balsam fir and white spruce
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(9), 3, FunctionalGroupIndex))%>%    #eastern white pine
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(36, 35), 4, FunctionalGroupIndex)) %>% #black spruce
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(7), 5, FunctionalGroupIndex)) %>% #tamarack, ceder
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(30, 31, 33, 42), 6, FunctionalGroupIndex)) %>% #northern hardwoods
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(37, 38, 41), 7, FunctionalGroupIndex)) %>% #aspen
#   mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(25, 26, 28, 29, 27, 32, 43, 40, 39, 55), 8, FunctionalGroupIndex)) %>% #southern harwoods
#   # mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(), 9, FunctionalGroupIndex)) %>% #wet broadleaf 
#   # mutate(FunctionalGroupIndex = ifelse(SPGRPCD %in% c(), 10, FunctionalGroupIndex)) %>% #shrubs
#   left_join(func_table %>% dplyr::select(FunctionalGroupIndex, KLAI, MaximumLAI))
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-


sppToUseAll <- c("ABBA","ACNE2","ACRU","ACSA2","ACSA3","BEPA","FRNI","FRPE","LALA","PIBA2","PIGL","PIMA","PIRE","PIST","POBA2","POGR4","POTR5","QUAL",  "QUEL","QUMA2","QURU","QUVE","THOC2","TIAM","ULAM")

speciesREF <- read_excel("D:/Minnesota/TreeMap/REF_SPECIES.xlsx")
speciesREF$SpeciesCode <- speciesREF$SPECIES_SYMBOL


sppCrosswalk <- speciesREF[speciesREF$SPECIES_SYMBOL %in% sppToUseAll, ] %>%
  arrange(SPECIES_SYMBOL) %>%
  dplyr::select(SpeciesCode, SPCD)

sppCrosswalkCombine <- tibble(SpeciesCode = sppToUseAll,
       SPCD = list(12, # Balsam fir
                   71, # Tamarack
                   94, # White spruce
                   95, # Black spruce
                   105, # Jack pine
                   125, # Red pine
                   129, # White pine
                   241, # Northern white cedar
                   313, # Boxelder
                   316, # Red maple
                   317, # Silver maple
                   318, # Sugar maple
                   375, # Paper birch
                   543, # Black ash
                   544, # Green ash
                   741, # Balsam poplar
                   743, # Bigtooth aspen
                   746, # Quaking aspen
                   802, # White oak
                   809, # Northern pin oak
                   823, # Bur oak
                   833, # Northern red oak
                   837, # Black oak
                   951, # American basswood
                   972)) # American Elm


sppToUse <- sppCrosswalk$SpeciesCode
spcdToUse <- sppCrosswalk$SPCD
allSPCD <- unique(trees$SPCD)

# Now to calculate per-tree LAI contribution and plot-level LAI
enoughTrees <- table(sitetrees$SPCD) %>% `[`(which(table(sitetrees$SPCD) > 100)) %>% names()

age.model <- lm(log(AGEDIA) ~ poly(log(DIA), 3) * as.factor(SPCD), data = sitetrees[!is.na(sitetrees$DIA) & !is.na(sitetrees$AGEDIA) & sitetrees$SPCD %in% enoughTrees, ])
age.model2 <- lm(log(AGEDIA) ~ poly(log(DIA), 3), data = sitetrees[!is.na(sitetrees$DIA) & !is.na(sitetrees$AGEDIA), ])

trees %>%
  mutate(plotYear = paste(PLT_CN, INVYR, sep = "_")) %>%
  right_join(., plotsToUse, by = c("PLT_CN" = "CN")) %>%
  mutate(DIA_CM = DIA * 2.54,
         HT_M = HT / 3.3808) %>%
  filter(STATUSCD == 1) %>%
  left_join()
```








```{r}
sort(unique(mnSpp$SPECIES_SYMBOL))


```






























