---
title: "Data Mining Final Project"
author: "Louis Goodall"
date: "02/05/2022"
output: pdf_document
---


```{r, warning = FALSE, message = FALSE}
library(data.table)
library(tidyverse)
library(gstat)
library(terra)
library(raster)
library(parallel)
library(rgdal)
library(spdep)
```



```{r, message = FALSE, warning= FALSE}
memory.limit(100000000000000)

DW_raster_coords <- read_csv("C:/Users/lagoodal/Downloads/DW_raster_coords.csv")
DW_raster_coords <- DW_raster_coords[DW_raster_coords$g_m2 >= 10,]
coordinates(DW_raster_coords) <- ~ x + y
crs(DW_raster_coords) <- crs("EPSG:26917")

v <- variogram(log(g_m2) ~ 1, DW_raster_coords)
#v <- read_csv("C:/Users/lagoodal/Desktop/v.csv")
m <- fit.variogram(v, vgm(c("Sph", "Gau", "Exp")))
plot(v,m)

# By looking at the variogram it appears as though there is no change
# in the autocorrealtion of the values present. In fact, it appears as 
# though there is no spatial autocorrealtion, implying that all of my
# values are random.
# Next I will do a Moran's I to test if there is spatial autocorrelation
```



```{r, message= FALSE, warning= FALSE}
# There is only one polygon for the Piedmont so doing Moran's I
# the way that we were taught in class is out. Here is an attempt to 
# do Moran's I using just point data with no polygons
DW_raster_coords <- read_csv("C:/Users/lagoodal/Downloads/DW_raster_coords.csv")
DW_raster_coords <- DW_raster_coords[DW_raster_coords$g_m2 >= 10,]
# DW_distances <- as.matrix(dist(cbind(DW_raster_coords$x, DW_raster_coords$y)))

# The distance matrix is too big to allocate to a vector (13.5Gb)
# and I am not sure about how to get around this

# DW_distances_inv <- 1/DW_distances
# diag(DW_distances_inv) <- 0
# moran(DW_raster_coords$g_m2, DW_distances_inv)
```









