---
title: "Ecoregions"
output: pdf_document
date: "2024-02-08"
---


```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(terra)
library(tidyterra)
library(sf)
library(maps)
```



```{r}
set.seed(33)
# Create a get all .asc file function and then read them in to a list
get_asc_files <- function(directory){
  all_files <- list.files(path = directory, recursive = TRUE, full.names = TRUE)
  asc_files <- all_files[grep("\\.asc$", all_files, ignore.case = TRUE)]
  return(asc_files)
}
folder_path <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/PRISM Data"
asc_files <- get_asc_files(folder_path)
read_raster_files <- function(file_path){
  raster_list <- lapply(file_path, rast)
  return(raster_list)
}
prismRast <- read_raster_files(asc_files)
templateRaster <- rast("C:/Users/lagoodal/Desktop/All Raster Layers/Full Piedmont/MapCode_IC.tif")


# Rework the rasers so that they are projected to resemble the other ratsers to be used in LANDIS
extNC <- ext(-85, -75, 33, 37)
prismRast <- lapply(prismRast, function(x){crop(x, extNC)})
prismRast <- lapply(prismRast, function(x){project(x, templateRaster)})
piedmontBoundary <- st_read("C:/Users/lagoodal/Desktop/nc_eco_l3/Piedmont UTM 17N.shp")
prismRast <- lapply(prismRast, function(x){crop(x, piedmontBoundary[2])})
prismRast <- lapply(prismRast, function(x){mask(x, piedmontBoundary[2])})
prismRast <- lapply(prismRast, function(x){project(x, templateRaster)})
tempRast <- list(prismRast[[1]], prismRast[[2]], prismRast[[3]], prismRast[[4]], prismRast[[5]], prismRast[[6]], prismRast[[7]])
precipRast <- list(prismRast[[8]], prismRast[[9]], prismRast[[10]], prismRast[[11]], prismRast[[12]], prismRast[[13]], prismRast[[14]])


# # Calculate mean temp and total precipitation, to stack them we need to convert them to raster::raster (Raster Layer vs. SpatRaster)
# tempRasters <- lapply(tempRast, function(x){raster::raster(x)})
# tempStack <- raster::stack(tempRasters)
# tempMean <- raster::calc(tempStack, mean)
# precipRasters <- lapply(precipRast, function(x){raster::raster(x)})
# precipStack <- raster::stack(precipRasters)
# precipSum <- raster::calc(precipStack, sum)
# rasterStack <- raster::stack(precipMean, tempMean)



tempStack <- c(tempRast[[1]], tempRast[[2]], tempRast[[3]], tempRast[[4]], tempRast[[5]], tempRast[[6]], tempRast[[7]])
precipStack <- c(precipRast[[1]], precipRast[[2]], precipRast[[3]], precipRast[[4]], precipRast[[5]], precipRast[[6]], precipRast[[7]])


tempMean <- app(tempStack, mean)
precipSum <- app(precipStack, sum)

rasterStack <- c(precipSum, tempMean)



# Set NAs to 0 so that when the clustering takes place it doesn't end up all weird
rasterStack$sum[is.na(rasterStack$sum),] <- 0
rasterStack$mean[is.na(rasterStack$mean),] <- 0

# Scale the values and then perform k-means clustering
scaleP <- scale(rasterStack$sum)
scaleT <- scale(rasterStack$mean)
scaleStack <- c(scaleP, scaleT)
scaleDf <- as.data.frame(scaleStack)
Classification <- kmeans(na.omit(scaleDf), 4, iter.max = 10, nstart = 25)
# hist(Classification$cluster)
cluster <- as.integer(Classification$cluster)
outputMatrix <- matrix(cluster, nrow = nrow(precipMean), ncol = ncol(precipMean), byrow = TRUE)

# newoutputRaster <- raster::raster(outputMatrix, xmn = xmin(precipMean), ymn = ymin(precipMean), xmx = xmax(precipMean), ymx = ymax(precipMean), crs = "epsg:26917")

# This one is all good
ecoregionsTest <- rast(outputMatrix, extent = ext(templateRaster), crs = crs(templateRaster))


# Read in treeMap to use as template for non-forest/forest cells
ecoregionTemplate <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Clipped Piedmont/finalTreeMap.tif")

# Make all active cells 1 and non-active 0
# Still integers here
ecoregionTemplate <- terra::classify(ecoregionTemplate,
                     matrix(c(0,0,0,1,99999,1), ncol = 3, byrow = TRUE))


# Read in clipped landscape to clip the full Piedmont
clippedPiedmont.shp <- st_read("C:/Users/lagoodal/Desktop/All Raster Layers/standsraster/Clipped Shapefile/clippedHUC.shp")


# Project and then crop and mask the climate/ecoregions
# Still good here
ecoregions <- project(ecoregionsTest, ecoregionTemplate, method = "near")
ecoregions <- crop(ecoregions, clippedPiedmont.shp) %>% mask(., clippedPiedmont.shp)
ecoregions <- mask(ecoregions, ecoregionTemplate, maskvalue = 0)
# values(ecoregions) %>% as.data.frame() %>% drop_na() %>% group_by(lyr.1) %>% summarise(n = n())

ecoregions <- ifel(ecoregions == is.nan(ecoregions), 0,
          ifel(ecoregions == 3, 2,
               ifel(ecoregions == 2, 0, ecoregions)))

plot(ecoregions)


# writeRaster(ecoregions,
#             filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Clipped Piedmont/ecoregions.tif",
#             datatype = "INT1U",
#             NAflag = 0,
#             overwrite = TRUE)

```

# Create a ecoregions map to be used foe testing harvesting

```{r}
# Bring in the normal ecoregions map and the management areas map
ecoregionsHarvest <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Clipped Piedmont/ecoregions.tif")
managementAreasRast <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Harvest/managementAreas.tif")

plot(ecoregionsHarvest)
plot(managementAreasRast)
# Make all the values 0 and then make all the ones that we are intersted in 1
values(ecoregionsHarvest) <- 0
ecoregionsHarvest[540:639,1150:1249] <- 1
plot(ecoregionsHarvest)

writeRaster(ecoregionsHarvest,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Biomass Testing/ecoregionsHarvest.tif",
            datatype = "INT1U",
            overwrite = TRUE,
            NAflag = NA)

test <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/treeMap/Biomass Testing/ecoregionsHarvest.tif")
plot(test)
test2 <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/Small Landscape/Clipped Piedmont/ecoregionsHarvest.tif")
plot(test2)
```








```{r}
treeMap <- rast("C:/Users/lagoodal/Desktop/Tree Map/Data/TreeMap2016.tif")
piedmontBoundary <- st_read("C:/Users/lagoodal/Desktop/nc_eco_l3/Piedmont UTM 17N.shp") %>%
  st_transform(crs = crs(treeMap))
# crs(treeMap)
# plot(treeMap)
extent <- ext(1e6, 1.85e6, 1.2e6, 1.8e6)
r <- crop(treeMap, extent)
rm(treeMap)

r <- crop(r, piedmontBoundary[2])
r <- mask(r, piedmontBoundary[2])

# Actrivate the FORTYPCD layer
activeCat(r) <- 2

rDf <- as.data.frame(r, xy = TRUE, na.rm = FALSE)

rDf <- rDf %>% mutate(FORTYPCD = as.integer(paste0(FORTYPCD)))



rDf$FORTYP <- ifelse(rDf$FORTYPCD %in% 100:199, "Softwoods",
          ifelse(rDf$FORTYPCD %in% 400:499, "Oak-Pine",
               ifelse(rDf$FORTYPCD %in% 500:599, "Oak-Hickory",
                    ifelse(rDf$FORTYPCD %in% 600:699, "Oak-Gum-Cypress",
                         ifelse(rDf$FORTYPCD %in% 700:799, "Elm-Ash-Cottonwood",
                              ifelse(rDf$FORTYPCD %in% 800:899, "Maple-Beech-Birch",
                                   ifelse(rDf$FORTYPCD %in% 900:950, "Aspen-Birch",
                                          ifelse(rDf$FORTYPCD == "NA", NA, "Other"))))))))

r <- as_spatraster(rDf[,c(1,2,4)], xycols = 1:2, crs = crs(r))

r <- project(r, "epsg:26917", method = "near")

plot(r, col = c("black", "black", "black", "pink", "yellow", "black", "forestgreen"))
```


treeMapDf <- data.table::fread("C:/Users/lagoodal/Desktop/Tree Map/Data/TreeMap2016_tree_table.csv")
piedmontTMdf <- treeMapDf %>% filter(tm_id %in% values(r))
rm(treeMapDf)



```












