---
title: "Untitled"
author: "Louis Goodall"
date: "2022-08-04"
output: pdf_document
---

```{r}
library(tidyverse)
library(rFIA)
library(ggrepel)
library(raster)
library(rgdal)
library(fs)
library(terra)
library(sf)
library(proj4)
```


```{r}
### Data needed for the analysis
# Five States = NC, GA, VA, SC & TN. The four states surrounding NC from which the dissimilarity index will select the PLT_CN from
# cr = The cells contained within the Raster Stack. had to convert to data.frame, although it was originally a matrix
# species.list = the spp codes for the top 29 spp found in the piedmont (No. 50 was 999/Unknown) so it was removed
species.list <- c(68,110,129,131,132,316,373,403,409,531,541,544,602,611,621,693,711,731,762,802,806,812,831,832,833,835,837,971,972)
```


```{r}
# Read in TREE Table data from NC and the 4 surrounding states which touch NC (GA, VA, SC, TN)
Five.States <- read_csv("C:/Users/lagoodal/Desktop/5 States/fia.Five.States.csv")
# Filter out the species of interest (Top 29 by BA)
FIA <- Five.States %>%
  filter(SPCD %in% species.list)
# Extract unique plot numbers
uniquePLT.CN <- unique(FIA$PLT_CN)
# Order data y DIA in a descending order
FIA <- FIA[order(-FIA$DIA),]

cr<-read.csv("C:/Users/lagoodal/Desktop/cr.csv")
# cr<-cr[1:10000,]
# Loop to generate basal area from diameter values 
Plt_Df <- NULL
for (i in 1:length(uniquePLT.CN)){
  two <- NULL
  end <- NULL
  Plot <- uniquePLT.CN[i]
  FIA.BA <- FIA[FIA$PLT_CN==uniquePLT.CN[i],]
  JUVI <- sum(((FIA.BA$DIA[FIA.BA$SPCD==68]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==68])
  PIEC <- sum(((FIA.BA$DIA[FIA.BA$SPCD==110]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==110])
  PIST <- sum(((FIA.BA$DIA[FIA.BA$SPCD==129]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==129])
  PITA <- sum(((FIA.BA$DIA[FIA.BA$SPCD==131]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==131])
  PIVI <- sum(((FIA.BA$DIA[FIA.BA$SPCD==132]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==132])
  ACRU <- sum(((FIA.BA$DIA[FIA.BA$SPCD==316]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==316])
  BENI <- sum(((FIA.BA$DIA[FIA.BA$SPCD==373]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==373])
  CAGL <- sum(((FIA.BA$DIA[FIA.BA$SPCD==403]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==403])
  CAAL <- sum(((FIA.BA$DIA[FIA.BA$SPCD==409]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==409])
  FAGR <- sum(((FIA.BA$DIA[FIA.BA$SPCD==531]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==531])
  FRAM <- sum(((FIA.BA$DIA[FIA.BA$SPCD==541]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==541])
  FRPE <- sum(((FIA.BA$DIA[FIA.BA$SPCD==544]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==544])
  JUNI <- sum(((FIA.BA$DIA[FIA.BA$SPCD==602]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==602])
  LIST <- sum(((FIA.BA$DIA[FIA.BA$SPCD==611]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==611])
  LITU <- sum(((FIA.BA$DIA[FIA.BA$SPCD==621]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==621])
  NYSY <- sum(((FIA.BA$DIA[FIA.BA$SPCD==693]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==693])
  OXAR <- sum(((FIA.BA$DIA[FIA.BA$SPCD==711]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==711])
  PLOC <- sum(((FIA.BA$DIA[FIA.BA$SPCD==731]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==731])
  PRSE <- sum(((FIA.BA$DIA[FIA.BA$SPCD==762]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==762])
  QUAL <- sum(((FIA.BA$DIA[FIA.BA$SPCD==802]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==802])
  QUCO <- sum(((FIA.BA$DIA[FIA.BA$SPCD==806]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==806])
  QUFA <- sum(((FIA.BA$DIA[FIA.BA$SPCD==812]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==812])
  QUPH <- sum(((FIA.BA$DIA[FIA.BA$SPCD==831]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==831])
  QUPR <- sum(((FIA.BA$DIA[FIA.BA$SPCD==832]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==832])
  QURU <- sum(((FIA.BA$DIA[FIA.BA$SPCD==833]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==833])
  QUST <- sum(((FIA.BA$DIA[FIA.BA$SPCD==835]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==835])
  QUVE <- sum(((FIA.BA$DIA[FIA.BA$SPCD==837]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==837])
  ULAL <- sum(((FIA.BA$DIA[FIA.BA$SPCD==971]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==971])
  ULAM <- sum(((FIA.BA$DIA[FIA.BA$SPCD==972]^2)*0.005454)*FIA.BA$TPA_UNADJ[FIA.BA$SPCD==972])
  row <- cbind(Plot,JUVI,PIEC,PIST,PITA,PIVI,ACRU,BENI,CAGL,CAAL,FAGR,FRAM,FRPE,JUNI,LIST,LITU,NYSY,OXAR,PLOC,PRSE,QUAL,QUCO,QUFA,QUPH,QUPR,QURU,QUST,QUVE,ULAL,ULAM)
  Plt_Df <- rbind(Plt_Df, row)
}

# Sum each row for index
Plt_Df_Sums <- rowSums(Plt_Df[,-1])
Plt_Df_2 <- cbind(Plt_Df, Plt_Df_Sums)
Plt_CN <- Plt_Df_2[,1]
Plt_Df_2 <- Plt_Df[,-1]
Plt_Df_2 <- cbind(Plt_Df_2, Plt_CN)
Plt_Df_2 <- as.data.frame(Plt_Df_2)
Plt_Df_2
```


```{r}
# Create a threshold for which to remove low proportion trees
# This was done out of caution in regards to making sure that trees with a low basal area are not over distributed
# Original threshold was 0.5, but that removed too many trees from the landscape due to it being less than Sumper
Threshold <- 1
cr_bi <- cr
Sum <- rowSums(cr_bi)

# Calculate total basal area for each row
totalBA <- sum(Sum, na.rm = T)
cr_bi <- cbind(cr_bi,Sum)
Sumper <- Sum*Threshold
cr_bi <- cbind(cr_bi,Sumper)
# View(as.data.frame(cr_bi))
test1 <- cr_bi[459415,]
#cr_bi[cr_bi < Sumper] <- 0
# View(as.data.frame(cr_bi[459415,]))
# Remove Sumper column
cr_bi <- as.data.frame(cr_bi[,-31])
test1 <- as.data.frame(cr_bi[459415,])

# Create a marker to locate each raster cell
Marker <- as.data.frame(1:nrow(cr))
cr_bi <- cbind(cr_bi, Marker)
# Create the data frame and change column names
colnames(cr_bi) <- c("JUVI","PIEC","PIST","PITA","PIVI","ACRU","BENI","CAGL","CAAL","FAGR","FRAM","FRPE","JUNI","LIST","LITU","NYSY","OXAR","PLOC","PRSE","QUAL","QUCO","QUFA","QUPH","QUPR","QURU","QUST","QUVE","ULAL","ULAM", "Sum", "Cell")
# Isolate all the empty cells so that we don't need to process them
zeros=cr_bi[(cr_bi[,1]==0 &cr_bi[,2]==0&
                   cr_bi[,3]==0&
                   cr_bi[,4]==0&
                   cr_bi[,5]==0&
                   cr_bi[,6]==0&
                   cr_bi[,7]==0&
                   cr_bi[,8]==0&
                   cr_bi[,9]==0&
                   cr_bi[,10]==0&
                   cr_bi[,11]==0&
                  cr_bi[,12]==0&
                  cr_bi[,13]==0&
               cr_bi[,14]==0&
               cr_bi[,15]==0&
               cr_bi[,16]==0&
               cr_bi[,17]==0&
               cr_bi[,18]==0&
               cr_bi[,19]==0&
               cr_bi[,20]==0&
               cr_bi[,21]==0&
               cr_bi[,22]==0&
               cr_bi[,23]==0&
               cr_bi[,24]==0&
               cr_bi[,25]==0&
               cr_bi[,26]==0&
               cr_bi[,27]==0&
               cr_bi[,28]==0&
               cr_bi[,29]==0),]


cr_bi_spp <- cr_bi[!(cr_bi[,1]==0 &cr_bi[,2]==0&
                    cr_bi[,3]==0&
                    cr_bi[,4]==0&
                    cr_bi[,5]==0&
                    cr_bi[,6]==0&
                    cr_bi[,7]==0&
                    cr_bi[,8]==0&
                    cr_bi[,9]==0&
                    cr_bi[,10]==0&
                    cr_bi[,11]==0&
                    cr_bi[,12]==0&
                    cr_bi[,13]==0&
                    cr_bi[,14]==0&
                    cr_bi[,15]==0&
                    cr_bi[,16]==0&
                    cr_bi[,17]==0&
                    cr_bi[,18]==0&
                    cr_bi[,19]==0&
                    cr_bi[,20]==0&
                    cr_bi[,21]==0&
                    cr_bi[,22]==0&
                    cr_bi[,23]==0&
                    cr_bi[,24]==0&
                    cr_bi[,25]==0&
                    cr_bi[,26]==0&
                    cr_bi[,27]==0&
                    cr_bi[,28]==0&
                    cr_bi[,29]==0),]
cr_bi_spp <- cr_bi_spp %>%
  drop_na()
####Do those two add up? they should
nrow(zeros) + nrow(cr_bi_spp)
cr_bi_spp <- as.data.frame(cr_bi_spp)
```



```{r}
memory.limit(1^16)
# Break cr_bi_spp up into subsets so that processing is easier
breaktest <- cr_bi_spp[90000:90100,]

breaklist1 <- cr_bi_spp[1:99999,]
breaklist2 <- cr_bi_spp[100000:199999,]
breaklist3 <- cr_bi_spp[200000:299999,]
breaklist4 <- cr_bi_spp[300000:399999,]
breaklist5 <- cr_bi_spp[400000:499999,]
breaklist6 <- cr_bi_spp[500000:599999,]
breaklist7 <- cr_bi_spp[600000:699999,]
breaklist8 <- cr_bi_spp[700000:741056,]


####This is the New_Sorensons_Similarity_function
New_Sorensons_Similarity<-function(Break,Plt_Df_2){####Break is just our cr_bi_spp broken down for speed
  ####Plt_DF_2 is the FIA product above
  ###Create Null objects to feed
   Log<-NULL
   Output<-NULL
   #Break<- breaklist1
   
   # j = 2
   # i = 2
   
   for(j in 1:nrow(Break)){
    print(j) 
    ##Each raster cell
    practice<-Break[j,]
    cell<-practice$Cell
    #print(cell)
    ####Get just the trees, no sums
    Sample1 <- Plt_Df_2
    Sample1$Sum=rowSums(Sample1[,-30]) ### Also this 
    Sample2<-practice[,c(-30,-31)] ### This is the change that needs to be made
    DeltaSamples<-NULL
    ###Preforming the Indexing
    if(!is.null(nrow(Sample2))){
      for(i in 2:length(Sample2)){
        #The top half of the function
        ###is a iterable maximum function.
        absw=abs(Sample2[,i]-Sample1[,i])
        mixed<-(Sample2[,i]+Sample1[,i])
        top<-(mixed-absw)
        halfed=.5*top
        DeltaSamples<-cbind(DeltaSamples,halfed)

      }
    }
    ###The sum of Top
    Top<-rowSums(DeltaSamples)
    ###The sum of bottom     
    Bottom<-Sample1$Sum+practice[,30]
    ###The index
    index<-Top/Bottom
    #print(index)
    ###Assign each site its index
    Plt_indexed<-cbind(Plt_Df_2,index)
    ###Find the one with the highest index
    Closestplot<-Plt_indexed%>%
                filter(index==max(index,na.rm = TRUE))#%>%
    Closestplot<-Closestplot[round(runif(1,1,nrow(Closestplot))),]
               #dplyr::select(Plt_CN)##(Plt_indexed$Plt_CN[Plt_indexed[,52]==max(Plt_indexed[,52],na.rm = TRUE)])
    #Record the score
    indexscore<-max(index,na.rm = TRUE)
    ###Create a row of the cell, its assinged plot and the score
    row<-cbind(cell,Closestplot$Plt_CN, Closestplot$index)    
    Output<-rbind(row,Output)
    ###This is for analysis log
    row2<-cbind(j,indexscore,Sample2)
    row3<-cbind(j,indexscore, Closestplot)
   colnames(row3)<-c("iteration","index","JUVI","PIEC","PIST","PITA","PIVI","ACRU","BENI","CAGL","CAAL","FAGR","FRAM","FRPE","JUNI","LIST","LITU","NYSY","OXAR","PLOC","PRSE","QUAL","QUCO","QUFA","QUPH","QUPR","QURU","QUST","QUVE","ULAL","ULAM",'PLT_CN',"index")
   colnames(row2)<-c("iteration","index","JUVI","PIEC","PIST","PITA","PIVI","ACRU","BENI","CAGL","CAAL","FAGR","FRAM","FRPE","JUNI","LIST","LITU","NYSY","OXAR","PLOC","PRSE","QUAL","QUCO","QUFA","QUPH","QUPR","QURU","QUST","QUVE","ULAL","ULAM")
    
    
    Log<-rbind(Log,row3)
    
    
  }
  
  return(list(Output,Log))
}

testing <- New_Sorensons_Similarity(breaktest, Plt_Df_2)
one<-as.data.frame(testing[1])
two<-as.data.frame(testing[2])
write.csv(two,"Testingoutputs.csv")
# FirstSection <- New_Sorensons_Similarity(breaklist1, Plt_Df_2)
# SecondSection <- New_Sorensons_Similarity(breaklist2, Plt_Df_2)
# ThirdSection <- New_Sorensons_Similarity(breaklist3, Plt_Df_2)
# FourthSection <- New_Sorensons_Similarity(breaklist4, Plt_Df_2)
# FifthSection <- New_Sorensons_Similarity(breaklist5, Plt_Df_2)
# SixthSection <- New_Sorensons_Similarity(breaklist6, Plt_Df_2)
SeventhSection <- New_Sorensons_Similarity(breaklist7, Plt_Df_2)
EighthSection <- New_Sorensons_Similarity(breaklist8, Plt_Df_2)
```




```{r}
Output <- rbind(as.data.frame(FirstSection[1]), as.data.frame(SecondSection[1]), as.data.frame(ThirdSection[1]), as.data.frame(FourthSection[1]), as.data.frame(FifthSection[1]), as.data.frame(SixthSection[1]), as.data.frame(SeventhSection[1]), as.data.frame(EighthSection[1]))

colnames(Output)[2] <- "Closestplot"

length(unique(Output$Closestplot))

Log <- rbind(as.data.frame(FirstSection[2]), as.data.frame(SecondSection[2]), as.data.frame(ThirdSection[2]), as.data.frame(FourthSection[2]), as.data.frame(FifthSection[2]), as.data.frame(SixthSection[2]), as.data.frame(SeventhSection[2]), as.data.frame(EighthSection[2]))


write_csv(Log, "C:/Users/lagoodal/Desktop/Sorenson 29 Spp/Log.csv")


```









