---
title: "Climate"
output: pdf_document
date: "2025-02-14"
---

```{r}
library(tidyverse)
```



```{r}
## Temperature
rbind(BNU_ESM_RCP45, MIROC_ESM_CHEM_RCP45, MRI_CGCM3_RCP45,CCSM4_RCP45,BNU_ESM_RCP85, MIROC_ESM_CHEM_RCP85, MRI_CGCM3_RCP85,CCSM4_RCP85) %>%
  ggplot(., aes(x = Year, y = airtemp, col = Model)) +
  geom_line() +
  theme_classic() +
  ylab("Mean Air Temp (°C)")

rbind(BNU_ESM_RCP45, MIROC_ESM_CHEM_RCP45, MRI_CGCM3_RCP45, CCSM4_RCP45, BNU_ESM_RCP85, MIROC_ESM_CHEM_RCP85, MRI_CGCM3_RCP85, CCSM4_RCP85) %>%
  mutate(RCP = ifelse(grepl("45", Model), "RCP45", "RCP85")) %>%
  ggplot(., aes(x = Year, y = airtemp, col = Model)) +
  geom_line(alpha = 0) +
  geom_smooth(se = FALSE, method = "lm") +
  theme_classic() +
  ylab("Mean Air Temp (°C)") +
  facet_wrap(~RCP)

## Precipitation
rbind(BNU_ESM_RCP45, MIROC_ESM_CHEM_RCP45, MRI_CGCM3_RCP45,CCSM4_RCP45,BNU_ESM_RCP85, MIROC_ESM_CHEM_RCP85, MRI_CGCM3_RCP85,CCSM4_RCP85) %>%
  ggplot(., aes(x = Year, y = sumppt, col = Model)) +
  geom_line() +
  theme_classic() +
  ylab("Total Precipitation (mm)")

rbind(BNU_ESM_RCP45, MIROC_ESM_CHEM_RCP45, MRI_CGCM3_RCP45, CCSM4_RCP45, BNU_ESM_RCP85, MIROC_ESM_CHEM_RCP85, MRI_CGCM3_RCP85, CCSM4_RCP85) %>%
  mutate(RCP = ifelse(grepl("45", Model), "RCP45", "RCP85")) %>%
  ggplot(., aes(x = Year, y = sumppt, col = Model)) +
  geom_line(alpha = 0) +
  geom_smooth(se = FALSE, method = "lm") +
  theme_classic() +
  ylab("Total Precipitation (mm)") +
  facet_wrap(~RCP)


rbind(BNU_ESM_RCP45,BNU_ESM_RCP85,MIROC_ESM_CHEM_RCP45,MIROC_ESM_CHEM_RCP85,MRI_CGCM3_RCP45,CCSM4_RCP45,MRI_CGCM3_RCP85,CCSM4_RCP85,CCSM4_RCP85) %>%
  group_by(Model) %>%
  summarise(varMeanPPT = sd(meanppt),
            varTotalPPT = sd(sumppt),
            varTemp = sd(airtemp)) %>%
  arrange(desc(varMeanPPT))

rbind(BNU_ESM_RCP45,BNU_ESM_RCP85,MIROC_ESM_CHEM_RCP45,MIROC_ESM_CHEM_RCP85,MRI_CGCM3_RCP45,CCSM4_RCP45,MRI_CGCM3_RCP85,CCSM4_RCP85,CCSM4_RCP85) %>%
  group_by(Model) %>%
  summarise(MeanPPT = mean(meanppt),
            TotalPPT = mean(sumppt),
            Temp = mean(airtemp)) %>%
  arrange(desc(TotalPPT))
```


```{r}
rbind(BNU_ESM_RCP45, MIROC_ESM_CHEM_RCP45, MRI_CGCM3_RCP45, CCSM4_RCP45, BNU_ESM_RCP85, MIROC_ESM_CHEM_RCP85, MRI_CGCM3_RCP85, CCSM4_RCP85) %>%
  mutate(RCP = ifelse(grepl("45", Model), "RCP45", "RCP85")) %>%
  arrange(desc(sumppt))

```




```{r}
totalBiomass10 <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL_Experiment/output/biomass/bio-TotalBiomass-10.img") %>% flip()
totalBiomass20 <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL_Experiment/output/biomass/bio-TotalBiomass-20.img") %>% flip()

plot(totalBiomass10)
plot(totalBiomass20)



```













