---
title: "Untitled"
output: pdf_document
date: "2025-04-04"
---

```{r, warning  = FALSE, message = FALSE}
library(tidyverse)
library(tidyterra)
library(terra)
library(vegan)
library(sf)
library(scico)
library(cowplot)
templateRaster <- rast("D:/Landis Outputs/Raster Template/templateRaster.tif")
species <- sort(c("JUVI","PIEC2","PIPA2","PIST","PITA","PIVI2","TAAS","TADI2","QUAL","QUCO2","QUFA","QULA3","QUNI","QUPH","QUPR2","QURU","QUST","QUVE","ACRU","CAAL27","CAGL8","FAGR","FRAM2","FRPE","LIST2","LITU","NYBI","NYSY","OXAR","PRSE2"))
```

# Create the initial rasters that will get processed

```{r}
#----TOTAL CARBON----#
mainDir <- "D:/Landis Outputs"
scenarios <- c("Resistance", "Resilience", "Transition")
rcps <- c("RCP45", "RCP85")
climates <- c("HSHV", "HSLV", "LSHV", "LSLV")
model_names <- c("BNU-ESM", "MIROC-ESM-CHEM", "MRI-CGCM3", "CCSM4")
runs <- paste0("run",1:5)
timesteps <- 80

rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("TotalC-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

carbonList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/CARBON/"
for (i in seq_along(carbonList)) {
  writeRaster(carbonList[[i]],
              filename = paste0(directory, names(carbonList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----ANPP----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("AG_NPP-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

anppList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/ANPP/"
for (i in seq_along(anppList)) {
  writeRaster(anppList[[i]],
              filename = paste0(directory, names(anppList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}


#----NEEC----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("ANEE-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

aneeList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/NEEC/"
for (i in seq_along(aneeList)) {
  writeRaster(aneeList[[i]],
              filename = paste0(directory, names(aneeList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----ANNUAL WATER BUDGET----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("Annual-water-budget-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

awbList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/AWB/"
for (i in seq_along(awbList)) {
  writeRaster(awbList[[i]],
              filename = paste0(directory, names(awbList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----SOMTC----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("SOMTC-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

somtcList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/SOMTC/"
for (i in seq_along(somtcList)) {
  writeRaster(somtcList[[i]],
              filename = paste0(directory, names(somtcList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----ABOVEGROUND BIOMASS----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("output/biomass/bio-TotalBiomass-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

agbList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/AGB/"
for (i in seq_along(agbList)) {
  writeRaster(agbList[[i]],
              filename = paste0(directory, names(agbList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----BIODIVERSITY----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          for (spp in species){
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("output/biomass/bio-", spp, "-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, timestep, spp, run, sep = "_")
          rasterList[[name]] <- raster
          }
        }
      }
    }
  }
}

combo_list <- expand.grid(scenario = scenarios, rcp = rcps, climate = climates) 
diversityList <- list()
for (i in 1:nrow(combo_list)) {
  scenario <- combo_list$scenario[i]
  rcp <- combo_list$rcp[i]
  climate <- combo_list$climate[i]
  species_rasters <- list()
  for (spp in species) {
    spp_rasters <- list()
    for (run in runs) {
      for (timestep in timesteps) {
        img_file <- file.path(mainDir, scenario, rcp, climate, run, 
                              paste0("output/biomass/bio-", spp, "-", timestep, ".img"))
        r <- rast(img_file)
        crs(r) <- "epsg:26917"
        r <- flip(r)
        ext(r) <- ext(templateRaster)
        spp_rasters <- append(spp_rasters, r)
      }
    }
    species_rasters[[spp]] <- app(spp_rasters, "mean")
  }
  species_stack <- rast(species_rasters)
  df <- as.data.frame(species_stack, xy = TRUE)
  df <- df %>% 
    mutate(rowSums = rowSums(select(., -x, -y))) %>%
    filter(rowSums > 0)
  shannon_vals <- diversity(df[,-c(1,2, ncol(df))], "shannon")
  df$H <- shannon_vals
  diversity_rast <- as_spatraster(df[, c("x", "y", "H")], crs = "epsg:26917") %>% 
                    project(., templateRaster)
  map_name <- paste(scenario, rcp, climate, sep = "_")
  # names(diversity_rast) <- map_name
  diversityList[[map_name]] <- diversity_rast
}

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/DIVERSITY/"
for (i in names(diversityMaps)) {
  writeRaster(diversityMaps[[i]],
              filename = paste0(directory, i,".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

#----TOTAL HARVEST----#
rasterList <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (timestep in timesteps) {
          img_file <- file.path(mainDir, scenario, rcp, climate, run, paste0("Harvest/biomass-removed-", timestep, ".img"))
          raster <- rast(img_file)
          crs(raster) <- "epsg:26917"
          raster <- flip(raster)
          ext(raster) <- ext(templateRaster)
          name <- paste(scenario, rcp, climate, run, timestep, sep = "_")
          rasterList[[name]] <- raster
        }
      }
    }
  }
}

Resistance_RCP45_HSHV <- c(rasterList[[1]],rasterList[[2]],rasterList[[3]],rasterList[[4]],rasterList[[5]]) %>% app(., "mean")
names(Resistance_RCP45_HSHV) <- "Resistance_RCP45_HSHV"
Resistance_RCP45_HSLV <- c(rasterList[[6]],rasterList[[7]],rasterList[[8]],rasterList[[9]],rasterList[[10]]) %>% app(., "mean")
names(Resistance_RCP45_HSLV) <- "Resistance_RCP45_HSLV"
Resistance_RCP45_LSHV <- c(rasterList[[11]],rasterList[[12]],rasterList[[13]],rasterList[[14]],rasterList[[15]]) %>% app(., "mean")
names(Resistance_RCP45_LSHV) <- "Resistance_RCP45_LSHV"
Resistance_RCP45_LSLV <- c(rasterList[[16]],rasterList[[17]],rasterList[[18]],rasterList[[19]],rasterList[[20]]) %>% app(., "mean")
names(Resistance_RCP45_LSLV) <- "Resistance_RCP45_LSLV"
Resistance_RCP85_HSHV <- c(rasterList[[21]],rasterList[[22]],rasterList[[23]],rasterList[[24]],rasterList[[25]]) %>% app(., "mean")
names(Resistance_RCP85_HSHV) <- "Resistance_RCP85_HSHV"
Resistance_RCP85_HSLV <- c(rasterList[[26]],rasterList[[27]],rasterList[[28]],rasterList[[29]],rasterList[[30]]) %>% app(., "mean")
names(Resistance_RCP85_HSLV) <- "Resistance_RCP85_HSLV"
Resistance_RCP85_LSHV <- c(rasterList[[31]],rasterList[[32]],rasterList[[33]],rasterList[[34]],rasterList[[35]]) %>% app(., "mean")
names(Resistance_RCP85_LSHV) <- "Resistance_RCP85_LSHV"
Resistance_RCP85_LSLV <- c(rasterList[[36]],rasterList[[37]],rasterList[[38]],rasterList[[39]],rasterList[[40]]) %>% app(., "mean")
names(Resistance_RCP85_LSLV) <- "Resistance_RCP85_LSLV"
Resilience_RCP45_HSHV <- c(rasterList[[41]],rasterList[[42]],rasterList[[43]],rasterList[[44]],rasterList[[45]]) %>% app(., "mean")
names(Resilience_RCP45_HSHV) <- "Resilience_RCP45_HSHV"
Resilience_RCP45_HSLV <- c(rasterList[[46]],rasterList[[47]],rasterList[[48]],rasterList[[49]],rasterList[[50]]) %>% app(., "mean")
names(Resilience_RCP45_HSLV) <- "Resilience_RCP45_HSLV"
Resilience_RCP45_LSHV <- c(rasterList[[51]],rasterList[[52]],rasterList[[53]],rasterList[[54]],rasterList[[55]]) %>% app(., "mean")
names(Resilience_RCP45_LSHV) <- "Resilience_RCP45_LSHV"
Resilience_RCP45_LSLV <- c(rasterList[[56]],rasterList[[57]],rasterList[[58]],rasterList[[59]],rasterList[[60]]) %>% app(., "mean")
names(Resilience_RCP45_LSLV) <- "Resilience_RCP45_LSLV"
Resilience_RCP85_HSHV <- c(rasterList[[61]],rasterList[[62]],rasterList[[63]],rasterList[[64]],rasterList[[65]]) %>% app(., "mean")
names(Resilience_RCP85_HSHV) <- "Resilience_RCP85_HSHV"
Resilience_RCP85_HSLV <- c(rasterList[[66]],rasterList[[67]],rasterList[[68]],rasterList[[69]],rasterList[[70]]) %>% app(., "mean")
names(Resilience_RCP85_HSLV) <- "Resilience_RCP85_HSLV"
Resilience_RCP85_LSHV <- c(rasterList[[71]],rasterList[[72]],rasterList[[73]],rasterList[[74]],rasterList[[75]]) %>% app(., "mean")
names(Resilience_RCP85_LSHV) <- "Resilience_RCP85_LSHV"
Resilience_RCP85_LSLV <- c(rasterList[[76]],rasterList[[77]],rasterList[[78]],rasterList[[79]],rasterList[[80]]) %>% app(., "mean")
names(Resilience_RCP85_LSLV) <- "Resilience_RCP85_LSLV"
Transition_RCP45_HSHV <- c(rasterList[[81]],rasterList[[82]],rasterList[[83]],rasterList[[84]],rasterList[[85]]) %>% app(., "mean")
names(Transition_RCP45_HSHV) <- "Transition_RCP45_HSHV"
Transition_RCP45_HSLV <- c(rasterList[[86]],rasterList[[87]],rasterList[[88]],rasterList[[89]],rasterList[[90]]) %>% app(., "mean")
names(Transition_RCP45_HSLV) <- "Transition_RCP45_HSLV"
Transition_RCP45_LSHV <- c(rasterList[[91]],rasterList[[92]],rasterList[[93]],rasterList[[94]],rasterList[[95]]) %>% app(., "mean")
names(Transition_RCP45_LSHV) <- "Transition_RCP45_LSHV"
Transition_RCP45_LSLV <- c(rasterList[[96]],rasterList[[97]],rasterList[[98]],rasterList[[99]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP45_LSLV) <- "Transition_RCP45_LSLV"
Transition_RCP85_HSHV <- c(rasterList[[101]],rasterList[[102]],rasterList[[103]],rasterList[[104]],rasterList[[105]]) %>% app(., "mean")
names(Transition_RCP85_HSHV) <- "Transition_RCP85_HSHV"
Transition_RCP85_HSLV <- c(rasterList[[106]],rasterList[[107]],rasterList[[108]],rasterList[[109]],rasterList[[100]]) %>% app(., "mean")
names(Transition_RCP85_HSLV) <- "Transition_RCP85_HSLV"
Transition_RCP85_LSHV <- c(rasterList[[111]],rasterList[[112]],rasterList[[113]],rasterList[[114]],rasterList[[115]]) %>% app(., "mean")
names(Transition_RCP85_LSHV) <- "Transition_RCP85_LSHV"
Transition_RCP85_LSLV <- c(rasterList[[116]],rasterList[[117]],rasterList[[118]],rasterList[[119]],rasterList[[120]]) %>% app(., "mean")
names(Transition_RCP85_LSLV) <- "Transition_RCP85_LSLV"

harvestList <- list(Resistance_RCP45_HSHV,Resilience_RCP45_HSHV,Transition_RCP45_HSHV,Resistance_RCP85_HSHV,Resilience_RCP85_HSHV,Transition_RCP85_HSHV,Resistance_RCP45_HSLV,Resilience_RCP45_HSLV,Transition_RCP45_HSLV,Resistance_RCP85_HSLV,Resilience_RCP85_HSLV,Transition_RCP85_HSLV,Resistance_RCP45_LSHV,Resilience_RCP45_LSHV,Transition_RCP45_LSHV,Resistance_RCP85_LSHV,Resilience_RCP85_LSHV,Transition_RCP85_LSHV,Resistance_RCP45_LSLV,Resilience_RCP45_LSLV,Transition_RCP45_LSLV,Resistance_RCP85_LSLV,Resilience_RCP85_LSLV,Transition_RCP85_LSLV)

directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/HARVEST/"
for (i in seq_along(harvestList)) {
  writeRaster(harvestList[[i]],
              filename = paste0(directory, names(harvestList[[i]]),".tif"),
              NAflag = 0,
              datatype = "FLT4S",
              overwrite = TRUE)
}

sort(c("Carbon","ANPP","NEEC","AWB","SOMTC","AGB","H","Harvest"))
```

# Data prep and main for loop running
# This is where I built the for loop, but I will be running it as an
# R script on the HPC

```{r}
mainDir <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/HPC_ES_MAPS/Rasters/"
colNames <- c("x","y","AGB","ANPP","AWB","Carbon","H","NEEC","SOMTC")
subfolders <- list.dirs(mainDir, recursive = FALSE)
get_rasters_from_subfolder <- function(folder) {
  rasters <- list.files(folder, pattern = "\\.tif$", full.names = TRUE)
  raster_list <- lapply(rasters, rast)
  names(raster_list) <- tools::file_path_sans_ext(basename(rasters))
  return(raster_list)
}
all_subfolder_rasters <- lapply(subfolders, get_rasters_from_subfolder)
all_raster_names <- unique(unlist(lapply(all_subfolder_rasters, names)))
grouped_rasters <- lapply(all_raster_names, function(name) {
  lapply(all_subfolder_rasters, function(subfolder) {
    if (name %in% names(subfolder)) subfolder[[name]] else NULL
  }) %>% compact()
})
names(grouped_rasters) <- all_raster_names
normaliseRasters <- function(rasters){
  lapply(rasters, function(r){
    r <- app(r, function(x) ifelse(x == 0, NA, x))
    r_min <- global(r, "min", na.rm = TRUE)[[1]]
    r_max <- global(r, "max", na.rm = TRUE)[[1]]
    (r - r_min) / (r_max - r_min)
  })
}
normalized_groups <- lapply(grouped_rasters, normaliseRasters)
stacked_rasters <- lapply(normalized_groups, function(x) {rast(x)})

mapNames <- c("Resilience_RCP45_HSHV","Resilience_RCP45_HSLV","Resilience_RCP45_LSHV","Resilience_RCP45_LSLV","Resilience_RCP85_HSHV","Resilience_RCP85_HSLV","Resilience_RCP85_LSHV","Resilience_RCP85_LSLV","Resistance_RCP45_HSHV","Resistance_RCP45_HSLV","Resistance_RCP45_LSHV","Resistance_RCP45_LSLV","Resistance_RCP85_HSHV","Resistance_RCP85_HSLV","Resistance_RCP85_LSHV","Resistance_RCP85_LSLV","Transition_RCP45_HSHV","Transition_RCP45_HSLV","Transition_RCP45_LSHV","Transition_RCP45_LSLV","Transition_RCP85_HSHV","Transition_RCP85_HSLV","Transition_RCP85_LSHV","Transition_RCP85_LSLV")

# Function akin to terra::mosaic except you can add in an overlap
makeTilesWithOverlap <- function(r, tile_width, tile_height, overlap = 0, 
                                 filename_template = NULL, overwrite = FALSE) {
  ext_r <- ext(r)
  xmin <- ext_r[1]
  xmax <- ext_r[2]
  ymin <- ext_r[3]
  ymax <- ext_r[4]
  x_tiles <- ceiling((xmax - xmin) / tile_width)
  y_tiles <- ceiling((ymax - ymin) / tile_height)
  tiles <- list()
  count <- 1
  
  for (i in 0:(x_tiles - 1)) {
    for (j in 0:(y_tiles - 1)) {
      x_start <- xmin + i * tile_width - overlap
      x_end   <- xmin + (i + 1) * tile_width + overlap
      y_start <- ymin + j * tile_height - overlap
      y_end   <- ymin + (j + 1) * tile_height + overlap
      
      # Clamp to raster extent
      x_start <- max(x_start, xmin)
      x_end   <- min(x_end, xmax)
      y_start <- max(y_start, ymin)
      y_end   <- min(y_end, ymax)
      tile_extent <- ext(x_start, x_end, y_start, y_end)
      tile_rast <- crop(r, tile_extent)
      if (!is.null(filename_template)) {
        filename <- sprintf(filename_template, count)
        writeRaster(tile_rast, filename, overwrite = overwrite)
      }
      tiles[[count]] <- tile_rast
      count <- count + 1
    }
  }
  return(tiles)
}


# Start the map creating for loop
rasterFiles <- list.files(path = "C:/Users/lagoodal/Desktop/Raster Dump/TEST/", pattern = "\\.tif$", full.name = TRUE)
rasterList <- list()

for (i in seq_along(stacked_rasters)) {
  currentRast <- stacked_rasters[[i]]
  mapName <- mapNames[i]
  
  # Remove previous tiles from Storage folder if they are there to save space
  filesToDelete <- list.files("C:/Users/lagoodal/Desktop/Raster Dump/TEST/", pattern = "\\.tif$", full.names = TRUE)
  if (length(filesToDelete) > 0) file.remove(filesToDelete)
  
  # Create tiles with some overlap
  filename_template <- paste0("C:/Users/lagoodal/Desktop/Raster Dump/TEST/", mapName, "_tile_%03d.tif")
  makeTilesWithOverlap(currentRast, tile_width = 5000, tile_height = 5000, overlap = 300,
  filename_template = filename_template, overwrite = TRUE)
  
  # Process the tiles and create distance matrices for each tile
  rasterFiles <- list.files("C:/Users/lagoodal/Desktop/Raster Dump/TEST/", pattern = "\\.tif$", full.names = TRUE)
  for (j in rasterFiles) {
  r <- rast(j)
  coords <- r %>% as.data.frame(xy = TRUE, na.rm = FALSE) %>% select(x, y)
  valMatrix <- values(r)
  valMatrix <- valMatrix[, -6] # Remove harvest column for now
  if (all(is.nan(valMatrix))) {
    valMatrix[is.nan(valMatrix)] <- 0
  } else {
    for (k in seq_len(ncol(valMatrix))) {
      colVals <- valMatrix[, k]
      colMedian <- if (all(is.na(colVals))) 0 else median(colVals, na.rm = TRUE)
      colVals[is.na(colVals)] <- colMedian
      valMatrix[, k] <- colVals
    }
  }
  distMatrix <- vegdist(valMatrix, method = "bray")
  distMatrixDf <- as.data.frame(as.matrix(distMatrix))
  distMatrixDf <- cbind(coords, rowSums(distMatrixDf)) %>% rename("Sum" = "rowSums(distMatrixDf)")
  raster <- as_spatraster(distMatrixDf, crs = "epsg:26917")
  # Only mask if r[[1]] has values
  if (any(!is.na(values(r[[1]])))) {
    raster <- mask(raster, r[[1]])
  } else {
    warning(paste("Skipping mask for", j, ": mask raster has no values."))
    # Optional: raster stays unmasked
  }
  rasterList[[j]] <- raster
  }
  # Mosaic and smooth the raster, then save to folder
  mosaicRast <- mosaic(sprc(rasterList), fun = "mean")
  mosaicRast <- focal(mosaicRast, w = matrix(1, 3, 3), fun = mean, na.rm = TRUE) # May comment out later
  mosaicRast <- mask(mosaicRast, currentRast[[1]])
  output_path <- paste0("C:/Users/lagoodal/Desktop/Dissertation Stuff/ES_MAP_OUTPUT/", mapName, ".tif")
  writeRaster(mosaicRast, filename = output_path, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}




```



```{r}
clippedPiedmont.shp <- st_read("C:/Users/lagoodal/Desktop/All Raster Layers/standsraster/Clipped Shapefile/clippedPiedmont.shp")

# Read in the final raster maps
rasterList <- list()
rasterFiles <- list.files("C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Finished", full.names = TRUE)
rasterList <- lapply(rasterFiles, function(x) rast(x))

allDf <- list()
for (i in seq_along(rasterList)) {
  r <- rasterList[[i]]
  sourceName <- tools::file_path_sans_ext(basename(sources(r)))
  df <- as.data.frame(r, xy = TRUE) %>%
    mutate(Name = sourceName)
  allDf[[i]] <- df
}
allDf <- do.call(rbind, allDf)

# Normalise the values to be between 0 - 1
allDf <- allDf %>% mutate(Sum = (Sum - min(Sum)) / (max(Sum) - min(Sum)))

# Split the raster name into prescription, climate and RCP columns
allDf <- allDf %>%
  mutate(Name = as.character(Name)) %>%
  bind_cols(
    str_split_fixed(allDf$Name, "_", 3) %>%
      as.data.frame() %>%
      setNames(c("Prescription", "RCP", "Model")))


ggplot(allDf) +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  theme_classic() +
  facet_grid(Prescription ~ RCP)


ggplot(allDf) +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_gradient2(low = "red",
                       mid = "forestgreen",
                       high = "#0b349d",
                       name = "LOUIS",
                       midpoint = 0.5) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)


# MAYBE THESE ONES
ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "berlin", name = "Tradeoff", direction = -1) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)
ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "bukavu", name = "Tradeoff", direction = -1) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)
ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "lipari", name = "Tradeoff", direction = -1) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)

ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "berlin", name = "Tradeoff") +
  theme_classic() +
  facet_grid(RCP ~ Prescription)
ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "bukavu", name = "Tradeoff") +
  theme_classic() +
  facet_grid(RCP ~ Prescription)
ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = Sum)) +
  scale_fill_scico(palette = "lipari", name = "Tradeoff") +
  theme_classic() +
  facet_grid(RCP ~ Prescription)





allDf$bins <- cut(
  allDf$Sum,
  breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
  labels = c("0-0.2", "0.2-0.4", "0.4-0.6", "0.6-0.8", "0.8-1"),
  include.lowest = TRUE,
  right = FALSE
)

# allDf$bins <- factor(allDf$bins, levels = c("0–0.2", "0.2–0.4", "0.4–0.6", "0.6–0.8", "0.8–1"))

 allDf <- allDf %>%
  mutate(Prescription = factor(Prescription, levels = c("Resistance", "Resilience", "Transition")))

ggplot(allDf) +
  geom_sf(data = clippedPiedmont.shp, col = "black", fill = "gray88") +
  geom_raster(aes(x = x, y = y, fill = bins)) +
  scale_fill_viridis_d(option = "magma", direction = -1, name = "ES Tradeoff") +
  theme_classic() +
  labs(x = "Longitude", y = "Latitude") +
  facet_grid(Prescription ~ RCP) +
  theme(strip.text = element_text(size = 20),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 10))

allDf %>%
  filter(RCP == "RCP85", Prescription == "Resistance") %>%
  ggplot(., aes(x = Sum)) +
  geom_histogram(
    aes(fill = after_stat(x)),  # <-- fill based on bin center
    binwidth = 0.05,
    color = "black"
  ) +
  scale_fill_viridis_c(option = "magma", direction = -1, name = "ES Tradeoff") +
  scale_y_continuous(breaks = c(0, 1e5, 2e5, 3e5, 4e5, 5e5, 6e5), labels = c(0,10,20,20,40,50,60),
                     name = "Cell count in thousands", limits = c(0,6e5)) +
  theme_classic() +
  facet_grid(RCP ~ Prescription, scales = "fixed") +
  theme(strip.text = element_text(size = 20),
        axis.title = element_text(size = 15),
        axis.text = element_text(size = 20))


ggsave("C:/Users/lagoodal/Pictures/Vertical_Maps.png",
       plot = last_plot(),
       width = 15,
       height = 20,
       dpi = 300)



```











