---
title: "Finished Plots"
output: pdf_document
date: "2025-03-25"
---

```{r, messages = FALSE, warning = FALSE}
library(tidyverse)
library(terra)
library(sf)
library(spdep)
library(parallel)
library(nlme)
library(ez)
library(data.table)
options(scipen = 999)
templateRaster <- rast("D:/Landis Outputs/Raster Template/templateRaster.tif")
softwoods <- c("JUVI","PIEC2","PIPA2","PIST","PITA","PIVI2","TAAS","TADI2")
oaks <- c("QUAL","QUCO2","QUFA","QULA3","QUNI","QUPH","QUPR2","QURU","QUST","QUVE")
hardwoods <- c("ACRU","CAAL27","CAGL8","FAGR","FRAM2","FRPE","LIST2","LITU","NYBI","NYSY","OXAR","PRSE2")
```


# NECN Variables

```{r}
successionLogAllDf <- rbind(successionLog_BNU_ESM_RCP45_Resilience_All,
                       successionLog_BNU_ESM_RCP45_Resistance_All,
                       successionLog_BNU_ESM_RCP45_Transition_All,
                       successionLog_BNU_ESM_RCP85_Resilience_All,
                       successionLog_BNU_ESM_RCP85_Resistance_All,
                       successionLog_BNU_ESM_RCP85_Transition_All,
                       successionLog_CCSM4_RCP45_Resilience_All,
                       successionLog_CCSM4_RCP45_Resistance_All,
                       successionLog_CCSM4_RCP45_Transition_All,
                       successionLog_CCSM4_RCP85_Resilience_All,
                       successionLog_CCSM4_RCP85_Resistance_All,
                       successionLog_CCSM4_RCP85_Transition_All,
                       successionLog_MIROC_ESM_CHEM_RCP45_Resilience_All,
                       successionLog_MIROC_ESM_CHEM_RCP45_Resistance_All,
                       successionLog_MIROC_ESM_CHEM_RCP45_Transition_All,
                       successionLog_MIROC_ESM_CHEM_RCP85_Resilience_All,
                       successionLog_MIROC_ESM_CHEM_RCP85_Resistance_All,
                       successionLog_MIROC_ESM_CHEM_RCP85_Transition_All,
                       successionLog_MRI_CGCM3_RCP45_Resilience_All,
                       successionLog_MRI_CGCM3_RCP45_Resistance_All,
                       successionLog_MRI_CGCM3_RCP45_Transition_All,
                       successionLog_MRI_CGCM3_RCP85_Resilience_All,
                       successionLog_MRI_CGCM3_RCP85_Resistance_All,
                       successionLog_MRI_CGCM3_RCP85_Transition_All)


successionLog <- successionLogAllDf %>%
  group_by(Time, Model, RCP, Prescription) %>%
  summarise_all(mean)
successionLog$Prescription <- factor(successionLog$Prescription, levels = c("Resistance", "Resilience", "Transition"))


diversityDf <- rbind(diversity_BNU_ESM_RCP45_Resilience,
                       diversity_BNU_ESM_RCP45_Resistance,
                       diversity_BNU_ESM_RCP45_Transition,
                       diversity_BNU_ESM_RCP85_Resilience,
                       diversity_BNU_ESM_RCP85_Resistance,
                       diversity_BNU_ESM_RCP85_Transition,
                       diversity_CCSM4_RCP45_Resilience,
                       diversity_CCSM4_RCP45_Resistance,
                       diversity_CCSM4_RCP45_Transition,
                       diversity_CCSM4_RCP85_Resilience,
                       diversity_CCSM4_RCP85_Resistance,
                       diversity_CCSM4_RCP85_Transition,
                       diversity_MIROC_ESM_CHEM_RCP45_Resilience,
                       diversity_MIROC_ESM_CHEM_RCP45_Resistance,
                       diversity_MIROC_ESM_CHEM_RCP45_Transition,
                       diversity_MIROC_ESM_CHEM_RCP85_Resilience,
                       diversity_MIROC_ESM_CHEM_RCP85_Resistance,
                       diversity_MIROC_ESM_CHEM_RCP85_Transition,
                       diversity_MRI_CGCM3_RCP45_Resilience,
                       diversity_MRI_CGCM3_RCP45_Resistance,
                       diversity_MRI_CGCM3_RCP45_Transition,
                       diversity_MRI_CGCM3_RCP85_Resilience,
                       diversity_MRI_CGCM3_RCP85_Resistance,
                       diversity_MRI_CGCM3_RCP85_Transition)

filepath <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/Structural Diversity/"
files = list.files(path = filepath, pattern = "*.csv", full.names = TRUE)

strDivAllDf <- do.call(rbind, lapply(files, function(x) fread(x)))

strDivDf <- strDivAllDf %>%
  group_by(Time, RCP, Model, Prescription) %>%
  summarise(H = mean(H))

filepath <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/Cultural/"
files = list.files(path = filepath, pattern = "*.csv", full.names = TRUE)
culturalDf <- do.call(rbind, lapply(files, function(x) fread(x)))

filepath <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/FruitNut/"
files = list.files(path = filepath, pattern = "*.csv", full.names = TRUE)
fruitNutDf <- do.call(rbind, lapply(files, function(x) fread(x)))



AWBAllDf <- rbind(AWB_BNU_ESM_RCP45_ResilienceDf,
                  AWB_BNU_ESM_RCP45_ResistanceDf,
                  AWB_BNU_ESM_RCP45_TransitionDf,
                  AWB_BNU_ESM_RCP85_ResilienceDf,
                  AWB_BNU_ESM_RCP85_ResistanceDf,
                  AWB_BNU_ESM_RCP85_TransitionDf,
                  AWB_MIROC_ESM_CHEM_RCP45_ResilienceDf,
                  AWB_MIROC_ESM_CHEM_RCP45_ResistanceDf,
                  AWB_MIROC_ESM_CHEM_RCP45_TransitionDf,
                  AWB_MIROC_ESM_CHEM_RCP85_ResilienceDf,
                  AWB_MIROC_ESM_CHEM_RCP85_ResistanceDf,
                  AWB_MIROC_ESM_CHEM_RCP85_TransitionDf,
                  AWB_MRI_CGCM3_RCP45_ResilienceDf,
                  AWB_MRI_CGCM3_RCP45_ResistanceDf,
                  AWB_MRI_CGCM3_RCP45_TransitionDf,
                  AWB_MRI_CGCM3_RCP85_ResilienceDf,
                  AWB_MRI_CGCM3_RCP85_ResistanceDf,
                  AWB_MRI_CGCM3_RCP85_TransitionDf,
                  AWB_CCSM4_RCP45_ResilienceDf,
                  AWB_CCSM4_RCP45_ResistanceDf,
                  AWB_CCSM4_RCP45_TransitionDf,
                  AWB_CCSM4_RCP85_ResilienceDf,
                  AWB_CCSM4_RCP85_ResistanceDf,
                  AWB_CCSM4_RCP85_TransitionDf)

AWBDf <- AWBAllDf %>%
  # mutate(Model = sub("_[^_]+$", "", Model)) %>%
  group_by(Time, Model, RCP, Prescription) %>%
  summarise(AWB = mean(AWB))
```



```{r}
# NEEC
successionLog %>%
  filter(Time > 0) %>%
  ggplot(., aes(x = Time, y = NEEC, col = Model)) +
  geom_line(alpha = 1, size = 1.5) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  # geom_smooth(se = FALSE, method = "lm") +
  facet_grid(RCP ~ Prescription) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100)) +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"))

ggsave(filename = "NEEC.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)


# SOMTC
successionLog %>%
  filter(Time > 0) %>%
  ggplot(., aes(x = Time, y = SOMTC, col = Model)) +
  geom_line(alpha = 1, size = 1.5) +
  # geom_smooth(se = FALSE, method = "lm") +
  theme_classic() +
  # ylim(2400,4000) +
  facet_grid(RCP ~ Prescription) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100)) +
  scale_y_continuous(name = "SOMTC g/m2") +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"))

ggsave(filename = "SOMTC.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

# NPP
successionLog %>%
  mutate(NPP = (AG_NPPC + BG_NPPC) * 2) %>%
  filter(Time != 0) %>%
  ggplot(., aes(x = Time, y = NPP, col = Model)) +
  geom_line(alpha = 1, size = 1.5) +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  # geom_smooth(se = FALSE, method = "lm") +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100)) +
  # geom_hline(yintercept = 500) +
  # geom_hline(yintercept = 600) +
  ylab("Total Net Primary Productivity") +
  # geom_smooth(se = FALSE, method = "lm") +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"))

ggsave(filename = "ANPP.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)


# Aboveground Biomass
successionLog %>%
  filter(Time != 0) %>%
  ggplot(., aes(x = Time, y = AGB, col = Model)) +
  geom_line(alpha = 1, size = 1.5) +
  # geom_smooth(se = FALSE, method = "lm") +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100)) +
  scale_y_continuous(name = "AGB (kg/m2)", breaks = c(8e3,1e4,1.2e4), labels = c(8,10,12)) +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"))

ggsave(filename = "AGB.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

# H
diversityDf %>%
  filter(Time < 81 & Time > 0) %>%
  ggplot(., aes(x = Time, y = H, col = Model)) +
  geom_line(size = 1.5) +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"
  )) +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,20100))

ggsave(filename = "H.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

# aov.1 <- aov(H ~ Prescription * RCP * Model, data = diversityDf %>% filter(Time < 81 & Time > 0))
# summary(aov.1)

# Structural_H
strDivDf %>%
  filter(Time < 81 & Time > 0) %>%
  mutate(Prescription = factor(Prescription, levels = c("Resistance", "Resilience", "Transition"))) %>%
  ggplot(., aes(x = Time, y = H, col = Model)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"
  )) +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,20100)) +
  ylab("H (Structure)")

ggsave(filename = "Str_H.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

# AWB
AWBDf %>%
  ggplot(., aes(x = Time, y = AWB, col = Model)) +
  geom_line(size = 1.5) +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_color_manual(values = c(
    "BNU-ESM_RCP45" = "#ef233c",
    "BNU-ESM_RCP85" = "#d90429",
    "MIROC-ESM-CHEM_RCP45" = "#087e8b",
    "MIROC-ESM-CHEM_RCP85" = "#0b3954",
    "MRI-CGCM3_RCP45" = "#9d4edd",
    "MRI-CGCM3_RCP85" = "#5a189a",
    "CCSM4_RCP45" = "#ff8500",
    "CCSM4_RCP85" = "#ff6d00"
  )) +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,20100)) +
  ylab("AWB")

ggsave(filename = "AWB.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)


# Age Mortality
successionLog %>%
  filter(Time != 0) %>%
  mutate(Model = sub("_[^_]+$", "", Model)) %>%
  ggplot(., aes(x = Time, y = AgeMortality, col = Model)) +
  geom_line(alpha = 1, size = 1.5) +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100)) +
  ylab("Senesced Biomass (g/m2)")


# Fruit Nut Trees
fruitNutDf %>%
  mutate(Climate = case_when(
    Climate == "HSHV" ~ "BNU-ESM",
    Climate == "HSLV" ~ "MIROC-ESM-CHEM",
    Climate == "LSHV" ~ "MRI-CGCM3",
    TRUE ~ "CCSM4"
  ),
  SpeciesName = case_when(
    SpeciesName == "CAAL27" ~ "Carya tomentosa",
    SpeciesName == "CAGL8" ~ "Carya glabra",
    SpeciesName == "QUAL" ~ "Quercus alba",
    SpeciesName == "QUCO2" ~ "Quercus coccinea",
    SpeciesName == "QUFA" ~ "Quercus falcata",
    SpeciesName == "QULA3" ~ "Quercus laurifolia",
    SpeciesName == "QUNI" ~ "Quercus nigra",
    SpeciesName == "QUPH" ~ "Quercus phellos",
    SpeciesName == "QUPR2" ~ "Quercus montana",
    SpeciesName == "QURU" ~ "Quercus rubra",
    SpeciesName == "QUST" ~ "Quercus stellata",
    SpeciesName == "QUVE" ~ "Quercus velutina"
  ),
  Model = paste0(Climate,"_",RCP),
  Scenario = factor(Scenario, levels = c("Resistance", "Resilience", "Transition"))) %>%
  select(-Climate) %>%
  rename("Prescription" = "Scenario") %>%
  ggplot(., aes(x = Time, y = Score, fill = SpeciesName)) +
  geom_area() +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_fill_manual(values = c(
    "Carya tomentosa" = "#FFD700",
    "Carya glabra" = "#DAA520",
    "Quercus alba" = "#355E3B",
    "Quercus coccinea" = "#4B8B3B",
    "Quercus falcata" = "#6B8E23",
    "Quercus laurifolia" = "#228B22",
    "Quercus nigra" = "#2E8B57",
    "Quercus phellos" = "#3CB371",
    "Quercus montana" = "#8FBC8F",
    "Quercus rubra" = "#A0522D",
    "Quercus stellata" = "#CD853F",
    "Quercus velutina" = "#D2B48C"
  ), name = "Species") +
  scale_y_continuous(name = "Mg (Mature Trees)", breaks = c(0, 1e9, 2e9, 3e9), labels = c(0, 1e3, 2e3, 3e3)) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100))

ggsave(filename = "Fruit Nut.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

# Cultural Trees
culturalDf %>%
  mutate(Climate = case_when(
    Climate == "HSHV" ~ "BNU-ESM",
    Climate == "HSLV" ~ "MIROC-ESM-CHEM",
    Climate == "LSHV" ~ "MRI-CGCM3",
    TRUE ~ "CCSM4"
  ),
  SpeciesName = case_when(
    SpeciesName == "CAAL27" ~ "Carya tomentosa",
    SpeciesName == "CAGL8" ~ "Carya glabra",
    SpeciesName == "LITU" ~ "Liriodendron tulipifera",
    SpeciesName == "OXAR" ~ "Oxydendrum arboreum",
    SpeciesName == "QUAL" ~ "Quercus alba"
  ),
  Model = paste0(Climate,"_",RCP),
  Scenario = factor(Scenario, levels = c("Resistance", "Resilience", "Transition"))) %>%
  select(-Climate) %>%
  rename("Prescription" = "Scenario") %>%
  ggplot(., aes(x = Time, y = Score, fill = SpeciesName)) +
  geom_area() +
  theme_classic() +
  facet_grid(RCP ~ Prescription) +
  scale_fill_manual(values = c(
    "Carya tomentosa" = "#FFD700",
    "Carya glabra" = "#DAA520",
    "Quercus alba" = "#355E3B",
    "Liriodendron tulipifera" = "#9ACD32",
    "Oxydendrum arboreum" = "#B22222"
  ), name = "Species") +
  scale_y_continuous(name = "Mg (Mature Trees)", breaks = c(0, 5e8, 1e9, 1.5e9), labels = c(0, 5e2, 1e3, 1.5e3)) +
  scale_x_continuous(name = "Year", breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100))

ggsave(filename = "Cultural.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)
```



```{r}
#----ANNUAL WATER BUDGET----#
mainDir <- "D:/Landis Outputs"
scenarios <- c("Resistance", "Resilience", "Transition")
rcps <- c("RCP45", "RCP85")
climates <- c("HSHV", "HSLV", "LSHV", "LSLV")
runs <- paste0("run", 1:5)
years <- seq(10,80,10)

# Read in all the rasters to a list
combinedRasters <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        for (year in years){
        filePath <- file.path(mainDir, scenario, rcp, climate, run, paste0("Annual-water-budget-", year, ".img"))
        filename <- paste0(scenario, "_", rcp, "_", climate, "_", run, "_", "Annual-water-budget-", year)
        raster <- rast(filePath) %>% flip()
        crs(raster) <- "epsg:26917"
        combinedRasters[[filename]] <- raster
        }
      }
    }
  }
}

# Change names of climatic models
model_lookup <- c(
  HSHV = "BNU-ESM",
  HSLV = "MIROC-ESM-CHEM",
  LSHV = "MRI-CGCM3",
  LSLV = "CCSM4"
)

# Loop through all scenario combinations
all_results <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      combo_results <- list()
      for (year in years) {
        raster_keys <- paste0(scenario, "_", rcp, "_", climate, "_", runs, "_Annual-water-budget-", year)
        df <- map_dfc(raster_keys, ~ terra::values(combinedRasters[[.x]])) %>%
          setNames(runs) %>%
          pivot_longer(cols = everything(), names_to = "Run", values_to = "AWB") %>%
          filter(AWB > 0) %>%
          group_by(Run) %>%
          summarise(AWB = mean(AWB), .groups = "drop") %>%
          mutate(
            Time = year,
            Model = model_lookup[[climate]],
            RCP = rcp,
            Climate = climate,
            Scenario = scenario
          )
        combo_results[[as.character(year)]] <- df
      }
      all_results[[paste(scenario, rcp, climate, sep = "_")]] <- bind_rows(combo_results)
    }
  }
}

# Combine everything into one final tidy data frame
AWB_All_Results <- bind_rows(all_results)

AWBDf <- AWB_All_Results %>%
  group_by(Time, Model, RCP, Scenario) %>%
  summarise(AWB = mean(AWB)) %>%
  rename("Prescription" = "Scenario")

AWBDf$Group <- interaction(AWBDf$Prescription, AWBDf$RCP, AWBDf$Model, drop = TRUE)

AWBDf %>%
  ggplot(., aes(x = Time, y = AWB, col = Model)) +
  geom_line(size = 2, alpha = 1) +
  #geom_smooth(se = FALSE, method = "lm") +
  theme_classic() +
  facet_grid(RCP ~ Prescription)

AWBDf %>%
  ggplot(., aes(x = Time, y = AWB, col = Prescription)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(RCP ~ Model)

AWBDf %>%
  ggplot(., aes(x = Time, y = AWB, col = RCP)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(Prescription ~ Model)


AWBDf$Time <- as.factor(AWBDf$Time)
AWBDf$Prescription <- as.factor(AWBDf$Prescription)
AWBDf$RCP <- as.factor(AWBDf$RCP)
AWBDf$Model <- as.factor(AWBDf$Model)
AWBDf$Group <- as.factor(AWBDf$Group)

ezANOVA(data = AWBDf, dv = .(AWB), wid = Group, within = .(Time), between = .(Prescription, RCP, Model), detailed = TRUE)
```

# Harvest

```{r}
harvestDf <- rbind(harvest_BNU_ESM_RCP45_Resilience,
                   harvest_BNU_ESM_RCP45_Resistance,
                   harvest_BNU_ESM_RCP45_Transition,
                   harvest_BNU_ESM_RCP85_Resilience,
                   harvest_BNU_ESM_RCP85_Resistance,
                   harvest_BNU_ESM_RCP85_Transition,
                   harvest_MIROC_ESM_CHEM_RCP45_Resilience,
                   harvest_MIROC_ESM_CHEM_RCP45_Resistance,
                   harvest_MIROC_ESM_CHEM_RCP45_Transition,
                   harvest_MIROC_ESM_CHEM_RCP85_Resilience,
                   harvest_MIROC_ESM_CHEM_RCP85_Resistance,
                   harvest_MIROC_ESM_CHEM_RCP85_Transition,
                   harvest_MRI_CGCM3_RCP45_Resilience,
                   harvest_MRI_CGCM3_RCP45_Resistance,
                   harvest_MRI_CGCM3_RCP45_Transition,
                   harvest_MRI_CGCM3_RCP85_Resilience,
                   harvest_MRI_CGCM3_RCP85_Resistance,
                   harvest_MRI_CGCM3_RCP85_Transition,
                   harvest_CCSM4_RCP45_Resilience,
                   harvest_CCSM4_RCP45_Resistance,
                   harvest_CCSM4_RCP45_Transition,
                   harvest_CCSM4_RCP85_Resilience,
                   harvest_CCSM4_RCP85_Resistance,
                   harvest_CCSM4_RCP85_Transition)

harvestDfAll <- harvestDf[,c(1,2,70,38:67,69,3,71,72)] %>%
  pivot_longer(cols = c("BiomassHarvestedMg_ACRU":"BiomassHarvestedMg_TADI2"), names_to = "Species", values_to = "Harvested_Biomass") %>%
  group_by(Time, Species, Prescription, RCP, Model) %>%
  summarise(Total_Harvest = sum(Harvested_Biomass)) %>%
  mutate(Species = str_replace(Species, "^[^_]*_", ""),
         Model = sub("_[^_]+$", "", Model),
         FunctionalGroup = case_when(
           Species %in% hardwoods ~ "Hardwoods",
           Species %in% softwoods ~ "Softwoods",
           TRUE ~ "Oaks"
         )) %>%
  mutate(Prescription = factor(Prescription, levels = c("Resistance", "Resilience", "Transition")))



summary(aov(Total_Harvest ~ Prescription * Model * RCP, data = harvestDfAll))
# Only Prescription is significant

# Plot of average harvesting by functional group and prescription type across all RCPs and models
harvestDfAll %>%
  group_by(Time, Species, Prescription, RCP, FunctionalGroup) %>%
  summarise(Total_Harvest = mean(Total_Harvest) / 8) %>%
  ggplot(., aes(x = Time, y = Total_Harvest, fill = FunctionalGroup)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100), name = "Year") +
  scale_y_continuous(breaks = c(0,0.25e7,0.5e7,0.75e7,1e7,1.25e7), labels = c(0,2.5,5,7.5,10,12.5), name = "Biomass (Mg) millions") +
  facet_grid(~Prescription)


harvestDfAll %>%
  group_by(Time, Species, Prescription, RCP, Model, FunctionalGroup) %>%
  summarise(Total_Harvest = mean(Total_Harvest)/ 12) %>%
  ggplot(., aes(x = Time, y = Total_Harvest, fill = FunctionalGroup)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100), name = "Year") +
  scale_y_continuous(breaks = c(0,0.25e7,0.5e7,0.75e7,1e7,1.25e7), labels = c(0,2.5,5,7.5,10,12.5), name = "Biomass (Mg) millions") +
  facet_grid(Model~Prescription)

#----PROPORTIONS----#
sppPropBiomassDf <- rbind(propBiomass_BNU_ESM_RCP45_Resilience,
      propBiomass_BNU_ESM_RCP45_Resistance,
      propBiomass_BNU_ESM_RCP45_Transition,
      propBiomass_BNU_ESM_RCP85_Resilience,
      propBiomass_BNU_ESM_RCP85_Resistance,
      propBiomass_BNU_ESM_RCP85_Transition,
      propBiomass_MIROC_ESM_CHEM_RCP45_Resilience,
      propBiomass_MIROC_ESM_CHEM_RCP45_Resistance,
      propBiomass_MIROC_ESM_CHEM_RCP45_Transition,
      propBiomass_MIROC_ESM_CHEM_RCP85_Resilience,
      propBiomass_MIROC_ESM_CHEM_RCP85_Resistance,
      propBiomass_MIROC_ESM_CHEM_RCP85_Transition,
      propBiomass_MRI_CGCM3_RCP45_Resilience,
      propBiomass_MRI_CGCM3_RCP45_Resistance,
      propBiomass_MRI_CGCM3_RCP45_Transition,
      propBiomass_MRI_CGCM3_RCP85_Resilience,
      propBiomass_MRI_CGCM3_RCP85_Resistance,
      propBiomass_MRI_CGCM3_RCP85_Transition,
      propBiomass_CCSM4_RCP45_Resilience,
      propBiomass_CCSM4_RCP45_Resistance,
      propBiomass_CCSM4_RCP45_Transition,
      propBiomass_CCSM4_RCP85_Resilience,
      propBiomass_CCSM4_RCP85_Resistance,
      propBiomass_CCSM4_RCP85_Transition) %>%
  mutate(FunctionalGroup = case_when(
           Species %in% hardwoods ~ "Hardwoods",
           Species %in% softwoods ~ "Softwoods",
           TRUE ~ "Oaks"))

sppPropBiomassDf %>%
  ggplot(., aes(x = Time, y = Biomass_Percent / 4, fill = FunctionalGroup)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  facet_grid(RCP ~ Prescription)

propBiomass_BNU_ESM_RCP45_Resilience
propBiomass_BNU_ESM_RCP45_Resilience_AllRuns


#############################
harvestDfAll %>%
  group_by(Time, Species, Prescription, RCP, FunctionalGroup) %>%
  summarise(Total_Harvest = sum(Total_Harvest) / 8) %>%
  ggplot(., aes(x = Time, y = Total_Harvest, fill = FunctionalGroup)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100), name = "Year") +
  scale_y_continuous(breaks = c(0,1e7,2e7,3e7,4e7,5e7), labels = c(0,10,20,30,40,50), name = "") +
  facet_grid(~Prescription) +
  scale_fill_manual(values = c(
      "Hardwoods" = "#0072B2",
      "Softwoods" = "#E69F00",
      "Oaks"      = "#999999"
    )) +
  geom_hline(yintercept = 1337954 * 10)

harvestDfAll %>%
  group_by(Time, Species, Prescription, RCP, FunctionalGroup) %>%
  summarise(Total_Harvest = sum(Total_Harvest) / 8) %>%
  ggplot(., aes(x = Time, y = Total_Harvest, fill = FunctionalGroup)) +
  geom_bar(stat = "identity") +
  theme_classic() +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100), name = "Year") +
  scale_y_continuous(breaks = c(0,1e7,2e7,3e7,4e7,5e7), labels = c(0,10,20,30,40,50), name = "Millions of Mg") +
  facet_grid(~Prescription) +
  scale_fill_manual(values = c(
      "Hardwoods" = "seagreen4",
      "Softwoods" = "#E69F00",
      "Oaks"      = "firebrick3"
    ), name = "Functional Group")

ggsave(filename = "Total Harvest.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)
  

# harvestDfAll %>%
#   group_by(Time, Prescription) %>%
#   summarise(Total_Harvest = sum(Total_Harvest) / 8) %>%
#   ungroup() %>%
#   mutate(TenYearTotal = 1337954 * 10,
#          percent = (Total_Harvest / TenYearTotal) * 100) %>%
#   filter(percent < 100)
# 
# # Durham, Granville, Orange, Alamance, Person, Caswell
# (((846754 + 14686824 + 3511070 + 7107018 + 9934773 + 8866736) / 30.48) * 0.907185) / 0.47
# 2,846,711 # Volume
# 1,337,954 # Mg

```


# Reproduction & Establishment

```{r}
# Reproduction
mainDir <- "D:/Landis Outputs"
scenarios <- c("Resistance", "Resilience", "Transition")
rcps <- c("RCP45", "RCP85")
climates <- c("HSHV", "HSLV", "LSHV", "LSLV")
runs <- paste0("run", 1:5)

combinedData <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        filePath <- file.path(mainDir, scenario, rcp, climate, run, paste0("NECN-reproduction-log.csv"))
        data <- fread(filePath)
        data$Run <- run
        name <- paste(scenario, rcp, climate, run, sep = "_")
        combinedData[[name]] <- data
        for (name in names(combinedData)) {
          parts <- unlist(strsplit(name, "_"))
          combinedData[[name]]$Prescription <- parts[1]
          combinedData[[name]]$RCP <- parts[2]
          combinedData[[name]]$Model <- parts[3]
        }
      }
    }
  }
}

reproductionDfAll <- rbindlist(combinedData, fill = TRUE) %>% as.data.frame() %>% select(-V7)


reproductionDfAll <- reproductionDfAll %>%
  mutate(FunctionalGroup = case_when(
           SpeciesName %in% hardwoods ~ "Hardwoods",
           SpeciesName %in% softwoods ~ "Softwoods",
           TRUE ~ "Oaks"),
         Model = case_when(
           Model == "HSHV" ~ "BNU-ESM",
           Model == "HSLV" ~ "MIROC-ESM-CHEM",
           Model == "LSHV" ~ "MRI-CGCM3",
           TRUE ~ "CCSM4"))
data <- reproductionDfAll %>%
  group_by(Time, RCP, Prescription, Model, FunctionalGroup) %>%
  summarise(NumCohortsSeed = mean(NumCohortsSeed))

summary(aov(NumCohortsSeed ~ Prescription * RCP * Model, data = data))
# All 3 are significant, model is least significant, no interactions


summary(lm(NumCohortsSeed ~ Time * FunctionalGroup + Model + RCP + Prescription, data = data))

# Cohorts seeded by FunctionalGroup, RCP and Prescription across all model types
reproductionDfAll %>%
  group_by(Time, Model, Prescription, FunctionalGroup) %>%
  summarise(NumCohortsSeed = mean(NumCohortsSeed)) %>%
  ggplot(., aes(x = Time, y = NumCohortsSeed, col = FunctionalGroup)) +
  geom_line(size  = 1) +
  theme_classic() +
  facet_grid(Model ~ Prescription)


reproductionDfAll %>%
  group_by(Time, Model, Prescription, FunctionalGroup) %>%
  summarise(NumCohortsSeed = mean(NumCohortsSeed)) %>%
  #filter(Time == 10) %>%
  arrange(desc(NumCohortsSeed))

reproductionDfAll %>%
  group_by(Time, RCP, Model, FunctionalGroup) %>%
  summarise(NumCohortsSeed = mean(NumCohortsSeed)) %>%
  ggplot(., aes(x = Time, y = NumCohortsSeed, col = FunctionalGroup)) +
  geom_line(size = 1, alpha = 1) +
  # geom_smooth(se = FALSE, , method = "lm") +
  theme_classic() +
  facet_grid(RCP~Model)

reproductionDfAll %>%
  group_by(Time, Prescription, Model, FunctionalGroup) %>%
  summarise(NumCohortsSeed = mean(NumCohortsSeed)) %>%
  ggplot(., aes(x = Time, y = NumCohortsSeed, col = FunctionalGroup)) +
  geom_line(size = 1, alpha = 1) +
  # geom_smooth(se = FALSE, , method = "lm") +
  theme_classic() +
  facet_grid(Prescription~Model)


# Establishment
combinedData <- list()
for (scenario in scenarios) {
  for (rcp in rcps) {
    for (climate in climates) {
      for (run in runs) {
        filePath <- file.path(mainDir, scenario, rcp, climate, run, paste0("NECN-prob-establish-log.csv"))
        data <- fread(filePath)
        data$Run <- run
        name <- paste(scenario, rcp, climate, run, sep = "_")
        combinedData[[name]] <- data
        for (name in names(combinedData)) {
          parts <- unlist(strsplit(name, "_"))
          combinedData[[name]]$Prescription <- parts[1]
          combinedData[[name]]$RCP <- parts[2]
          combinedData[[name]]$Model <- parts[3]
        }
      }
    }
  }
}

establishmentDfAll <- rbindlist(combinedData, fill = TRUE) %>% as.data.frame() %>% select(-V15)

establishmentDfAll <- establishmentDfAll %>%
  group_by(Time, SpeciesName, Prescription, Model, RCP) %>%
  summarise(AvgProbEst = weighted.mean(x = AvgProbEst, w = rep(c(528897,24948), length.out = n()))) %>%
  mutate(Model = case_when(
    Model == "HSHV" ~ "BNU-ESM",
    Model == "HSLV" ~ "MIROC-ESM-CHEM",
    Model == "LSHV" ~ "MRI-CGCM3",
    TRUE ~ "CCSM4"
  ))
establishmentDfAll <- establishmentDfAll%>%
  mutate(FunctionalGroup = case_when(
           SpeciesName %in% hardwoods ~ "Hardwoods",
           SpeciesName %in% softwoods ~ "Softwoods",
           TRUE ~ "Oaks"))
data <- establishmentDfAll %>%
  group_by(Time, RCP, Prescription, Model, FunctionalGroup) %>%
  summarise(AvgProbEst = mean(AvgProbEst))

summary(aov(AvgProbEst ~ Prescription * RCP * Model + FunctionalGroup, data = data))


establishmentDfAll %>%
  group_by(Time, RCP, Model, FunctionalGroup) %>%
  summarise(AvgProbEst = mean(AvgProbEst)) %>%
  ggplot(., aes(x = Time, y = AvgProbEst, col = FunctionalGroup)) +
  geom_line(size  = 1) +
  theme_classic() +
  scale_color_manual(values = c(
      "Hardwoods" = "seagreen4",
      "Softwoods" = "#E69F00",
      "Oaks"      = "firebrick3"),
      name = "Functional Group") +
  facet_grid(RCP ~ Model) +
  scale_x_continuous(breaks = c(0,20,40,60,80), labels = c(2020,2040,2060,2080,2100), name = "Year") +
  ylab("Mean Probability of Establishment")

ggsave(filename = "Establishment Probability.png",
       path = "C:/Users/lagoodal/Pictures/",
       width = 16,
       height = 10,
       dpi = 300)

establishmentDfAll %>%
  group_by(Time, RCP, Prescription, FunctionalGroup) %>%
  summarise(AvgProbEst = mean(AvgProbEst)) %>%
  ggplot(., aes(x = Time, y = AvgProbEst, col = FunctionalGroup)) +
  geom_line(size  = 1) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)

rbind(BNU_ESM_RCP45,BNU_ESM_RCP85,MIROC_ESM_CHEM_RCP45,MIROC_ESM_CHEM_RCP85,MRI_CGCM3_RCP45,CCSM4_RCP45,MRI_CGCM3_RCP85,CCSM4_RCP85,CCSM4_RCP85) %>%
  group_by(Model) %>%
  summarise(sdMeanPPT = sd(meanppt),
            sdTotalPPT = sd(sumppt),
            sdTemp = sd(airtemp)) %>%
  arrange(desc(sdTotalPPT))


summary(lm(AvgProbEst ~ Time * FunctionalGroup + RCP + Prescription + Model, data = data))
  
```


# Structural Diversity

```{r}
filepath <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 2/Structural Diversity/"
files = list.files(path = filepath, pattern = "*.csv", full.names = TRUE)

strDivAllDf <- do.call(rbind, lapply(files, function(x) fread(x)))

strDivDf <- strDivAllDf %>%
  group_by(Time, RCP, Model, Prescription) %>%
  summarise(H = mean(H))

strDivDf %>%
  mutate(Model = sub("_[^_]+$", "", Model)) %>%
  filter(Time != 0 & Time < 81) %>%
  ggplot(., aes(x = Time, y = H, col = Model)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(RCP ~ Prescription)

strDivDf %>%
  mutate(Model = sub("_[^_]+$", "", Model)) %>%
  filter(Time != 0 & Time < 81) %>%
  ggplot(., aes(x = Time, y = H, col = Prescription)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(RCP ~ Model)

strDivDf %>%
  mutate(Model = sub("_[^_]+$", "", Model)) %>%
  filter(Time != 0 & Time < 81) %>%
  ggplot(., aes(x = Time, y = H, col = RCP)) +
  geom_line(size = 2) +
  theme_classic() +
  facet_grid(Model ~ Prescription)

aov.1 <- aov(H ~ Prescription * RCP * Model, data = strDivDf)
summary(aov.1)
TukeyHSD(aov.1)

summary(lm(H ~ Time*Prescription*RCP*Model, data = strDivDf))



# File paths
files <- list.files(
  path = "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Rasters/Structure Maps",
  pattern = "\\.tif$",
  full.names = TRUE
)

# Clean names for each raster
raster_names <- basename(files)

# Set up cluster (use available cores minus 1)
n_cores <- detectCores() - 1
cl <- makeCluster(n_cores)

# Export necessary objects & libraries to cluster
clusterExport(cl, varlist = c("files", "raster_names"), envir = environment())
clusterEvalQ(cl, {
  library(terra)
  library(spdep)
})

# Define the parallel task
results_list <- parLapply(cl, seq_along(files), function(i) {
  r <- rast(files[i])

  # Optional: downsample if needed
  # r <- aggregate(r, fact = 2)

  vals <- values(r)[,1]
  idx <- which(!is.na(vals))
  coords <- xyFromCell(r, idx)
  vals <- vals[idx]

  nb <- dnearneigh(coords, 0, 100)
  lw <- nb2listw(nb, style = "W", zero.policy = TRUE)
  mi <- moran.test(vals, lw, zero.policy = TRUE)

  return(data.frame(
    Raster = raster_names[i],
    Moran_I = mi$estimate["Moran I statistic"],
    Expected_I = mi$estimate["Expectation"],
    SD = mi$estimate["Standard deviate"],
    P_value = mi$p.value,
    stringsAsFactors = FALSE
  ))
})

# Stop the cluster

stopCluster(cl)

# Combine results into one data frame
results <- do.call(rbind, results_list)

# View results
print(results)

1+1
```










