---
title: "Untitled"
output: pdf_document
date: "2025-10-24"
---

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(terra)
library(sf)
templateRaster <- rast("D:/Landis Outputs/Raster Template/templateRaster.tif")
Piedmont.shp <- st_read("C:/Users/lagoodal/Desktop/All Raster Layers/standsraster/Clipped Shapefile/clippedPiedmont.shp")
gc()
```


```{r}
#----ABOVEGROUND BIOMASS----#
directory <- "D:/Hurricane_LANDIS"
rcps <- c("NORM", "HINT")
climates <- c("LSLV", "HSLV")
runs <- paste0("run", 1:3)
prescriptions <- c("Resistance", "Resilience", "Transition")
timesteps <- seq(10,80,10)

rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "output/biomass/bio-TotalBiomass-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "AGB")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----ANPP----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "NECN/AG_NPP-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "ANPP")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----ANNUAL WATER BUDGET----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "NECN/Annual-water-budget-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "AWB")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----CARBON----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "NECN/TotalC-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "CARBON")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----HARVEST----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "Harvest/biomass-removed-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "HARVEST")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----NEEC----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "NECN/ANEE-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "NEEC")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----SOMTC----#
rasterList <- list()
for (rcp in rcps) {
  for (climate in climates) {
    for (prescription in prescriptions) {
      for (run in runs) {
        for (timestep in timesteps) {
        filePath <- file.path(paste0(directory, "/", rcp, "/",
                                     climate, "/", prescription, "/",
                                     run, "/", "NECN/SOMTC-", timestep, ".img"))
        if (!file.exists(filePath)) {
          message("Skipping (file not found : ", filePath)
          next
        }
        raster <- rast(filePath) %>% flip()
        crs(raster) <- crs(templateRaster)
        ext(raster) <- ext(templateRaster)
        name <- paste(rcp, climate, prescription, run, timestep, sep = "_")
        names(raster) <- name
        rasterList[[name]] <- raster
        }
      }
    }
  }
}

rasterInfo <- tibble(
  name = names(rasterList),
  RCP = str_split(name, "_", simplify = TRUE)[, 1],
  Model = str_split(name, "_", simplify = TRUE)[, 2],
  Prescription = str_split(name, "_", simplify = TRUE)[, 3],
  Run = str_split(name, "_", simplify = TRUE)[, 4],
  Timestep = str_split(name, "_", simplify = TRUE)[, 5]
)

rasterInfo <- rasterInfo %>% mutate(groupID = paste(RCP, Model, Prescription, Timestep, sep = "_"))
averagedRasters <- list()
for (gid in unique(rasterInfo$groupID)) {
  subsetNames <- rasterInfo$name[rasterInfo$groupID == gid]
  rasters <- rast(rasterList[subsetNames])
  averaged <- mean(rasters, na.rm = TRUE)
  names(averaged) <- gid
  averagedRasters[[gid]] <- averaged
}

outDirectory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"
for (gid in names(averagedRasters)) {
  r <- averagedRasters[[gid]]
  parts <- strsplit(gid, "_")[[1]]
  rcp <- parts[1]
  model <- parts[2]
  prescription <- parts[3]
  timestep <- parts[4]
  timestepDir <- file.path(outDirectory, timestep, "SOMTC")
  dir.create(timestepDir, recursive = TRUE, showWarnings = FALSE)
  outFile <- file.path(timestepDir, paste0(prescription, "_", rcp, "_", model, ".tif"))
  writeRaster(r, filename = outFile, NAflag = 0, datatype = "FLT4S", overwrite = TRUE)
}
gc()

#----CULTURE----#
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Cultural_Maps"
combos <- expand.grid(Prescription = prescription, RCP = rcps, Climate = climates, Timestep = timesteps, stringsAsFactors = FALSE)
validCombos <- combos %>%
  mutate(inFile  = file.path(directory, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")),
           outDir  = file.path(outDirectory, Timestep, "CULTURE"),
         outFile = file.path(outDir, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")))
# Loop through each valid combination
for (i in seq_len(nrow(validCombos))) {
  filePath <- validCombos$inFile[i]
  outPath  <- validCombos$outFile[i]
  raster <- rast(filePath)
  crs(raster) <- crs(templateRaster)
  ext(raster) <- ext(templateRaster)
  writeRaster(raster, filename = outPath, overwrite = TRUE, datatype = "FLT4S", NAflag = 0)
}
gc()

#----DIVERSITY----#
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Species_Diversity_Maps/"
combos <- expand.grid(Prescription = prescription, RCP = rcps, Climate = climates, Timestep = timesteps, stringsAsFactors = FALSE)
validCombos <- combos %>%
  mutate(inFile  = file.path(directory, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")),
         outDir  = file.path(outDirectory, Timestep, "DIVERSITY"),
         outFile = file.path(outDir, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")))
# Loop through each valid combination
for (i in seq_len(nrow(validCombos))) {
  filePath <- validCombos$inFile[i]
  outPath  <- validCombos$outFile[i]
  raster <- rast(filePath)
  crs(raster) <- crs(templateRaster)
  ext(raster) <- ext(templateRaster)
  writeRaster(raster, filename = outPath, overwrite = TRUE, datatype = "FLT4S", NAflag = 0)
}
gc()

#----FRUITNUT----#
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Fruit_Nut_Maps/"
combos <- expand.grid(Prescription = prescription, RCP = rcps, Climate = climates, Timestep = timesteps, stringsAsFactors = FALSE)
validCombos <- combos %>%
  mutate(inFile  = file.path(directory, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")),
         outDir  = file.path(outDirectory, Timestep, "FRUITNUT"),
         outFile = file.path(outDir, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")))
# Loop through each valid combination
for (i in seq_len(nrow(validCombos))) {
  filePath <- validCombos$inFile[i]
  outPath  <- validCombos$outFile[i]
  raster <- rast(filePath)
  crs(raster) <- crs(templateRaster)
  ext(raster) <- ext(templateRaster)
  writeRaster(raster, filename = outPath, overwrite = TRUE, datatype = "FLT4S", NAflag = 0)
}
gc()

# STRUCTURAL DIVERSITY
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Structural_Diversity_Maps/"
combos <- expand.grid(Prescription = prescription, RCP = rcps, Climate = climates, Timestep = timesteps, stringsAsFactors = FALSE)
validCombos <- combos %>%
  mutate(inFile  = file.path(directory, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")),
         outDir  = file.path(outDirectory, Timestep, "STRUCTURE"),
         outFile = file.path(outDir, paste0(Prescription, "_", RCP, "_", Climate, "_", Timestep, ".tif")))
# Loop through each valid combination
for (i in seq_len(nrow(validCombos))) {
  filePath <- validCombos$inFile[i]
  outPath  <- validCombos$outFile[i]
  raster <- rast(filePath)
  crs(raster) <- crs(templateRaster)
  ext(raster) <- ext(templateRaster)
  writeRaster(raster, filename = outPath, overwrite = TRUE, datatype = "FLT4S", NAflag = 0)
}
gc()


```

# Cumulative Rasters

```{r}
# Top-level directory containing timestep folders
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/Hurricane_ES_MAPS"

# Scenarios and timesteps
scenarios <- c(
  "Transition_HINT_HSLV",
  "Resilience_HINT_HSLV",
  "Resistance_HINT_HSLV",
  "Transition_NORM_HSLV",
  "Resilience_NORM_HSLV",
  "Resistance_NORM_HSLV",
  "Transition_HINT_LSLV",
  "Resilience_HINT_LSLV",
  "Resistance_HINT_LSLV",
  "Transition_NORM_LSLV",
  "Resilience_NORM_LSLV",
  "Resistance_NORM_LSLV"
)

timesteps <- seq(10, 80, 10)

# Function to normalize a raster
normalize_raster <- function(r) {
  vals <- values(r, mat = FALSE)
  vals[is.na(vals)] <- 0
  minV <- min(vals)
  maxV <- max(vals)
  
  if (minV == maxV) {
    vals[] <- 0
  } else {
    vals <- (vals - minV) / (maxV - minV)
  }
  
  r[] <- vals
  return(r)
}

# Prepare a list to store cumulative rasters for each scenario
cumulativeScenarioRasters <- list()

for (scenario in scenarios) {
  timestepRasters <- list()
  
  for (timestep in timesteps) {
    timestepFolder <- file.path(directory, as.character(timestep))
    
    # get all subfolders in this timestep folder
    folders <- list.dirs(timestepFolder, recursive = FALSE)
    rasterList <- list()
    
    for (folder in folders) {
      pattern <- paste0(scenario, ".tif")
      filePath <- list.files(folder, pattern = pattern, full.names = TRUE)
      
      if (length(filePath) == 0) next  # skip if no file
      
      r <- rast(filePath[1])
      r <- normalize_raster(r)
      
      rasterList[[paste0(basename(folder), "_", timestep)]] <- r
    }
    
    # Only process if at least 2 rasters found
    if (length(rasterList) >= 2) {
      rasterNames <- names(rasterList)
      nRasters <- length(rasterList)
      tradeoffList <- list()
      
      for (i in 1:(nRasters - 1)) {
        for (j in (i + 1):nRasters) {
          rA <- rasterList[[i]]
          rB <- rasterList[[j]]
          tradeoff <- abs(rA - rB) * (1 / sqrt(2))
          pairName <- paste0(rasterNames[i], "_vs_", rasterNames[j])
          tradeoffList[[pairName]] <- tradeoff
        }
      }
      
      timestepStack <- rast(tradeoffList)
      timestepRasters[[as.character(timestep)]] <- app(timestepStack, sum, na.rm = TRUE)
    }
  }
  
  # Sum across all timesteps for this scenario
  if (length(timestepRasters) > 0) {
    scenarioStack <- rast(timestepRasters)
    cumulativeScenarioRasters[[scenario]] <- app(scenarioStack, sum, na.rm = TRUE)
  }
}

for (i in 1:12) {
writeRaster(cumulativeScenarioRasters[[i]],
            filename = paste0("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/HPC_ES_MAPS/Finished_Cumulative_Hurricane/",
                              names(cumulativeScenarioRasters)[i], ".tif"),
            NAflag = 0,
            overwrite = TRUE,
            datatype = "FLT4S")
}



plot(rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/HPC_ES_MAPS/Finished_Cumulative_Hurricane/Resilience_NORM_LSLV.tif"))
plot(rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/HPC_ES_MAPS/Finished_Cumulative_Hurricane/Resilience_HINT_LSLV.tif"))
plot(rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/HPC_ES_MAPS/Finished_Cumulative_Hurricane/Resilience_NORM_HSLV.tif"))
plot(rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/HPC_ES_MAPS/Finished_Cumulative_Hurricane/Resilience_HINT_HSLV.tif"))
```

# Map that shit

```{r}
directory <- "C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/LISA_Hurricane"
files <- list.files(directory, pattern = "top25\\.csv$", full.names = TRUE)

dfList <- list()
for (file in files) {
  filePath <- file.path(file)
  name <- basename(file)
  parts <- strsplit(name, "_")[[1]]
  df <- read_csv(filePath)
  df$Prescription <- parts[1]
  df$RCP <- parts[2]
  df$Model <- parts[3]
  dfList[[name]] <- df
}


mapsDf <- do.call(bind_rows, dfList)

mapsDf <- mapsDf %>%
  mutate(RCP = ifelse(RCP == "LISA", "Historical", RCP),
         Model = ifelse(Model == "top25.csv", "Historical", Model),
         Scenario = paste(Prescription, Model, RCP, sep = "_")) 

ggplot(mapsDf) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = orig_value)) +
  scale_fill_viridis_c(name = "Cumulative Tradeoff Score") +
  coord_sf() +
  theme_classic() +
  facet_wrap(~ Scenario) +
  theme(
    axis.text.x = element_text(),
    axis.text.y = element_text(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    strip.text = element_text(size = 14),
    legend.position = "right",
    legend.key.size = unit(3, "lines"),
    legend.title = element_text(size = 15)
  )

ggsave(width = 10, height = 6, dpi = 600,
       filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Images/Final_Cumulative_Maps.png")


ggplot(mapsDf %>% filter(Scenario == "Resilience_HSLV_HINT")) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = orig_value)) +
  scale_fill_viridis_c(name = "Cumulative Tradeoff Score") +
  coord_sf() +
  theme_classic() +
  # facet_wrap(~ Scenario) +
  theme(
    axis.text.x = element_text(),
    axis.text.y = element_text(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    strip.text = element_text(size = 14),
    legend.position = "none"
  )

ggsave(width = 10, height = 6, dpi = 600,
       filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Images/Final_Cumulative_Maps_Single.png")


gc()
```



```{r}
# directory <- "D:/Hurricane_LANDIS"
# climates <- c("HINT", "NORM")
# scenarios <- c("HSLV", "LSLV")
# prescriptions <- c("Resilience", "Resistance", "Transition")
# runs <- paste0("run", 1:5)

directory <- "D:/Hurricane_LANDIS"
climates <- c("HINT")
scenarios <- c("HSLV")
prescriptions <- c("Resilience")
runs <- paste0("run", 1:5)

# Mortality rasters for loop to read in and wrangle raster data
rasterList <- list()
for (climate in climates) {
  for (scenario in scenarios) {
    for (prescription in prescriptions) {
      for (run in runs) {
        hurricaneDir <- file.path(directory, climate, scenario, prescription, run, "hurricane")
        if (!dir.exists(hurricaneDir)) {
          message("Skipping (directory not found: ", hurricaneDir)
          next
        }
        mortalityRasters <- list.files(hurricaneDir, pattern = "mortality.*\\.tif$", full.names = TRUE, ignore.case = TRUE)
        if(length(mortalityRasters) == 0) {
          message("No mortality rasters found in: ", hurricaneDir)
          next
        }
        for (rasterPath in mortalityRasters) {
          message("Reading raster: ", rasterPath)
          r <- rast(rasterPath)
          name <- paste(climate, scenario, prescription, run, names(r), sep = "_")
          names(r) <- name
          crs(r) <- crs(templateRaster)
          ext(r) <- ext(templateRaster)
          r <- r %>% flip()
          r[r == 0] <- NA
          rasterList[[name]] <- r
        }
      }
    }
  }
}
gc()

# Convert into a dataframe for plotting with ggplot
dfList <- lapply(rasterList, function(r) {
  df <- as.data.frame(r, xy = TRUE)
  names(df)[3] <- "mortality"
  nameParts <- str_split(names(r), "_")[[1]]
  RCP <- nameParts[1]
  Model <- nameParts[2]
  Prescription <- nameParts[3]
  Run <- nameParts[4]
  fileName <- nameParts[5]
  matches <- str_match(fileName, "mortality-(\\d+)-(\\d+)")
  Year <- matches[,2]
  Hurricane <- matches[,3]
  df %>% mutate(RCP=RCP, Model=Model, Prescription=Prescription, Run=Run,
                Year=as.integer(Year), Hurricane=as.integer(Hurricane))
})


# Combine all data frames into one big table
allMortalityDF <- do.call(bind_rows, dfList)


# Number of storm events per cell
allMortalityDF$Hurricane <- as.numeric(as.character(allMortalityDF$Hurricane))



df <- allMortalityDF  %>%
  mutate(Scenario = paste(Prescription, Model, RCP, sep = "_")) %>%
  group_by(x, y, Scenario, Year) %>%
  summarise(avg_Hurricane = mean(Hurricane, na.rm = TRUE), .groups = "drop") %>%
  group_by(x, y, Scenario) %>%
  summarise(total_Hurricane = mean(avg_Hurricane), .groups = "drop")


allMortalityDF %>%
  group_by(x, y, RCP, Model, Prescription, Year) %>%
  summarise(avg_Hurricane = mean(Hurricane, na.rm = TRUE), .groups = "drop") %>%
  group_by(x, y, RCP, Model, Prescription) %>%
  summarise(total_Hurricane = sum(avg_Hurricane), .groups = "drop") %>%
  mutate(Scenario = paste(Prescription, Model, RCP, sep = "_"))

x <- allMortalityDF %>%
  mutate(Scenario = paste(Prescription, Model, RCP, sep = "_")) %>%
  group_by(x, y, Scenario) %>%
  summarise(total_Hurricane = n_distinct(interaction(Year, Hurricane)), .groups = "drop")

# rm(allMortalityDF)

x %>%
  ggplot(.) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = total_Hurricane))  +
  scale_fill_viridis_c(name = "Cumulative Hurricane Events") +
  theme_classic() +
  facet_wrap(~ Scenario)

ggplot(mapsDf) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = orig_value)) +
  scale_fill_viridis_c(name = "Cumulative Tradeoff Score") +
  coord_sf() +
  theme_classic() +
  facet_wrap(~ Scenario)



####################################################################
directory <- "D:/Hurricane_LANDIS"
climates <- c("HINT")
scenarios <- c("HSLV")
prescriptions <- c("Resilience")
runs <- paste0("run", 1:5)

# Mortality rasters for loop to read in and wrangle raster data
rasterList <- list()
for (climate in climates) {
  for (scenario in scenarios) {
    for (prescription in prescriptions) {
      for (run in runs) {
        hurricaneDir <- file.path(directory, climate, scenario, prescription, run, "hurricane")
        if (!dir.exists(hurricaneDir)) {
          message("Skipping (directory not found: ", hurricaneDir)
          next
        }
        windRasters <- list.files(hurricaneDir, pattern = "speeds.*\\.tif$", full.names = TRUE, ignore.case = TRUE)
        if(length(windRasters) == 0) {
          message("No mortality rasters found in: ", hurricaneDir)
          next
        }
        for (rasterPath in windRasters) {
          message("Reading raster: ", rasterPath)
          r <- rast(rasterPath)
          name <- paste(climate, scenario, prescription, run, names(r), sep = "_")
          names(r) <- name
          crs(r) <- crs(templateRaster)
          ext(r) <- ext(templateRaster)
          r <- r %>% flip()
          r[r == 0] <- NA
          rasterList[[name]] <- r
        }
      }
    }
  }
}

# Convert into a dataframe for plotting with ggplot
dfList <- lapply(rasterList, function(r) {
  df <- as.data.frame(r, xy = TRUE)
  names(df)[3] <- "windspeed"
  nameParts <- str_split(names(r), "_")[[1]]
  RCP <- nameParts[1]
  Model <- nameParts[2]
  Prescription <- nameParts[3]
  Run <- nameParts[4]
  fileName <- nameParts[5]
  matches <- str_match(fileName, "wind-speeds-(\\d+)-(\\d+)")
  Year <- matches[,2]
  Hurricane <- matches[,3]
  df %>% mutate(RCP=RCP, Model=Model, Prescription=Prescription, Run=Run,
                Year=as.integer(Year), Hurricane=as.integer(Hurricane))
})


allWindspeedDF <- do.call(bind_rows, dfList)

df <- allWindspeedDF %>%
  mutate(Scenario = paste(Prescription, Model, RCP, sep = "_")) %>%
  group_by(x, y, Scenario) %>%
  summarise(windspeed = max(windspeed))

data.table::fwrite(df, "/share/tcsi/lagoodal/R/Data/Dataframes/windspeedsDf.csv")

allWindspeedDF %>%
  mutate(Scenario = paste(Prescription, Model, RCP, sep = "_")) %>%
  group_by(x, y, Scenario) %>%
  summarise(windspeed = max(windspeed)) %>%
  ggplot(.) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = windspeed)) +
  scale_fill_viridis_c(name = "Max Windspeed (km/h)") +
  coord_sf() +
  theme_classic()

ggplot(mapsDf) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = orig_value)) +
  scale_fill_viridis_c(name = "Cumulative Tradeoff Score") +
  coord_sf() +
  theme_classic() +
  facet_wrap(~ Scenario) +
  theme(strip.text.x = element_text(size = 20))
  

```


```{r}
hurricaneMortalityDf <- data.table::fread("C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/hurricaneEvents.csv")
windspeedsDf <- data.table::fread("C:/Users/lagoodal/Documents/TEST HPC OUTPUTS/windspeedsDf.csv")

ggplot(windspeedsDf %>% filter(Scenario == "Resilience_HSLV_HINT")) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = windspeed)) +
  scale_fill_viridis_c(name = "Max Windspeed (km/h)") +
  coord_sf() +
  theme_classic() +
  facet_wrap(~ Scenario)

ggplot(x %>% filter(total_Hurricane < 11)) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = total_Hurricane))  +
  scale_fill_viridis_c(name = "Cumulative Hurricane Events") +
  theme_classic() +
  facet_wrap(~ Scenario)

ggplot(mapsDf %>% filter(Scenario == "Resilience_HSLV_HINT")) +
  geom_sf(data = Piedmont.shp, fill = "grey95", color = "black", linewidth = 0.4) +
  geom_raster(aes(x = x, y = y, fill = orig_value)) +
  scale_fill_viridis_c(name = "Cumulative Tradeoff Score") +
  coord_sf() +
  theme_classic() +
  facet_wrap(~ Scenario)


hurricaneMortalityDf

```














