---
title: "Untitled"
output: pdf_document
date: "2024-09-23"
---

```{r}
library(tidyverse)
library(terra)
library(tidyterra)
library(sf)
```



```{r}
# Read in data we will need
mgmtRast <- rast("C:/Users/lagoodal/Desktop/All Raster Layers/standsraster/clippedPiedmontOwnership.tif")
mgmtRastOG <- rast("C:/Users/lagoodal/Desktop/All Raster Layers/standsraster/clippedPiedmontOwnership.tif")
ecoregions <- rast("C:/Users/lagoodal/Desktop/All Raster Layers/Clipped Piedmont/ecoregions.tif")
ICMap <- rast("C:/Users/lagoodal/Desktop/All Raster Layers/Clipped Piedmont/MapCode_IC.tif")
mapCodeDf <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Clipped Test/test1/Final_table.csv")

# Reclassify some ecoregion values
ecoregions <- ifel(ecoregions == 0, NA,
                   ifel(ecoregions == 1, 1, ecoregions))

# Mask out NA ecoregions on management and ICMap raster
mgmtRast <- mask(mgmtRast, ecoregions)
ICMap <- mask(ICMap, ecoregions)

plot(ICMap)

# Cells per management area
mgmtRast %>%
  as.data.frame() %>%
  `colnames<-`("Class") %>%
  group_by(Class) %>%
  summarise(n = n())

# Create filtered management area map which will then be used to figure out what
# Map Codes are in which management area
mgmt1 <- ifel(mgmtRast == 1, 1, NA)
mgmt2 <- ifel(mgmtRast == 2, 2, NA)
mgmt3 <- ifel(mgmtRast == 3, 3, NA)
IC1 <- mask(ICMap, mgmt1)
IC2 <- mask(ICMap, mgmt2)
IC3 <- mask(ICMap, mgmt3)

# Get Map Codes by management area
IC1MC <- values(IC1) %>% as.data.frame() %>% drop_na() %>% unique()
IC2MC <- values(IC2) %>% as.data.frame() %>% drop_na() %>% unique()
IC3MC <- values(IC3) %>% as.data.frame() %>% drop_na() %>% unique()
IC1Df <- mapCodeDf %>% filter(MapCode %in% IC1MC$MapCode_IC)
IC2Df <- mapCodeDf %>% filter(MapCode %in% IC2MC$MapCode_IC)
IC3Df <- mapCodeDf %>% filter(MapCode %in% IC3MC$MapCode_IC)

# Create vectors that contain the species for each FORTYP classification
oakHickory <- c("QUAL","QUCO2","QUMO4","QUPH","QURU","QUST","QUVE","CATO6","CAGL8","LIST","LITU","ACRU")
oakPine <- c("QUAL","QUCO2","QUMO4","QUPH","QURU","QUST","QUVE","PITA","PIEC","PIVI2","PIPA","JUVI")
softwoods <- c("PIEC", "PIPA", "PIVI2", "PITA", "JUVI")

# Now to determine which cells fall into which forest type based upon their species and biomass values
IC1Df <- IC1Df %>%
  group_by(MapCode, SpeciesName) %>%
  summarise(biomass = sum(CohortBiomass)) %>%
  mutate(totalBiomass = sum(biomass),
         propBiomass = biomass / totalBiomass) %>%
  ungroup() %>%
  group_by(MapCode) %>%
  mutate(FORTYP = case_when(
    sum(propBiomass[SpeciesName == "PITA"]) > 0.9 ~ "LOBLOLLY",
    sum(propBiomass[SpeciesName %in% oakHickory]) > 0.6 ~ "OAK-HICKORY",
    sum(propBiomass[SpeciesName %in% oakPine]) > 0.6 ~ "OAK-PINE",
    sum(propBiomass[SpeciesName %in% softwoods]) >= 0.4 ~ "SOFTWOODS",
    TRUE ~ NA_character_
  )) %>%
  ungroup()


IC2Df <- IC2Df %>%
  group_by(MapCode, SpeciesName) %>%
  summarise(biomass = sum(CohortBiomass)) %>%
  mutate(totalBiomass = sum(biomass),
         propBiomass = biomass / totalBiomass) %>%
  ungroup() %>%
  group_by(MapCode) %>%
  mutate(FORTYP = case_when(
    sum(propBiomass[SpeciesName == "PITA"]) > 0.9 ~ "LOBLOLLY",
    sum(propBiomass[SpeciesName %in% oakHickory]) > 0.6 ~ "OAK-HICKORY",
    sum(propBiomass[SpeciesName %in% oakPine]) > 0.6 ~ "OAK-PINE",
    sum(propBiomass[SpeciesName %in% softwoods]) >= 0.4 ~ "SOFTWOODS",
    TRUE ~ NA_character_
  )) %>%
  ungroup()


IC3Df <- IC3Df %>%
  group_by(MapCode, SpeciesName) %>%
  summarise(biomass = sum(CohortBiomass)) %>%
  mutate(totalBiomass = sum(biomass),
         propBiomass = biomass / totalBiomass) %>%
  ungroup() %>%
  group_by(MapCode) %>%
  mutate(FORTYP = case_when(
    sum(propBiomass[SpeciesName == "PITA"]) > 0.9 ~ "LOBLOLLY",
    sum(propBiomass[SpeciesName %in% oakHickory]) > 0.6 ~ "OAK-HICKORY",
    sum(propBiomass[SpeciesName %in% oakPine]) > 0.6 ~ "OAK-PINE",
    sum(propBiomass[SpeciesName %in% softwoods]) >= 0.4 ~ "SOFTWOODS",
    TRUE ~ NA_character_
  )) %>%
  ungroup()

# Proportions of each FORTYP in each management zone
IC1Df %>% group_by(FORTYP) %>% summarise(n = n()) %>% mutate(total = sum(n), prop = n / total)
IC2Df %>% group_by(FORTYP) %>% summarise(n = n()) %>% mutate(total = sum(n), prop = n / total)
IC3Df %>% group_by(FORTYP) %>% summarise(n = n()) %>% mutate(total = sum(n), prop = n / total)

IC1MapCodes <- IC1Df %>% select(MapCode, FORTYP) %>% unique()
IC2MapCodes <- IC2Df %>% select(MapCode, FORTYP) %>% unique()
IC3MapCodes <- IC3Df %>% select(MapCode, FORTYP) %>% unique()

# Create a reclassified plot of all the FORTYPs in the Piedmont
# Get xy coord data and the corresponding MapCode and bind FORTYP into the dataframe
IC1MapDf <- as.data.frame(IC1, xy = TRUE)
IC1MapDf <- IC1MapDf %>% left_join(IC1MapCodes, by = c("MapCode_IC" = "MapCode"))
IC2MapDf <- as.data.frame(IC2, xy = TRUE)
IC2MapDf <- IC2MapDf %>% left_join(IC2MapCodes, by = c("MapCode_IC" = "MapCode"))
IC3MapDf <- as.data.frame(IC3, xy = TRUE)
IC3MapDf <- IC3MapDf %>% left_join(IC3MapCodes, by = c("MapCode_IC" = "MapCode"))
fortypMap <- rbind(IC1MapDf, IC2MapDf, IC3MapDf)
fortypMap <- as_spatraster(fortypMap[,c(1,2,4)])
plot(fortypMap)
```




```{r}
directory <- "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Harvest/"
file_list <- list.files(directory, pattern = "prescripts.*\\.img$", full.names = TRUE)
raster_list <- list()
for (file in file_list) {
  base_name <- tools::file_path_sans_ext(basename(file))
  new_name <- sub(".*-(.*)$", "\\1", base_name)
  raster <- rast(file)
  names(raster) <- new_name
  raster_list[[new_name]] <- raster
}

for (name in names(raster_list)) {
  raster <- raster_list[[name]]
  
  # Get the extent of the specified rows and columns
  extent_to_crop <- ext(440,510,450,700)
  
  # Crop the raster to the desired section
  cropped_raster <- crop(raster, extent_to_crop)
  
  # Get unique values from the cropped raster
  unique_values <- unique(values(cropped_raster), na.rm = TRUE)
  
  # Create a color palette with white for 0 and unique colors for other values
  color_palette <- c("white", rainbow(length(unique_values) - 1))
  names(color_palette) <- sort(unique_values)  # Map colors to unique values
  
  # Plot the cropped raster with the custom color palette
  plot(cropped_raster, col = color_palette, main = paste("Cropped Raster:", name), legend = TRUE)
}
```















