---
title: ''
output: pdf_document
date: "2024-11-18"
---

```{r}
library(tidyverse)
library(sf)
library(terra)
```

# Single Cell Runs

```{r}
# Create a single celled ecoregion
ecoregions <- rast("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/ecoregions1.tif")
plot(ecoregions)
singleCellEcoregion <- ecoregions
values(singleCellEcoregion) <- 0
singleCellEcoregion[500,500] <- 1
plot(singleCellEcoregion)

writeRaster(singleCellEcoregion,
            filename = "C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/SOSIEL Experiment/Rasters/singleCellEcoregion.tif",
            datatype = "INT1U",
            NAflag = NA,
            overwrite = TRUE)
```

## Test 1

```{r}
successionLog <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Soil Grid Data/Soil Testing/Single Cell/Test 1/NECN-succession-log.csv")

# Carbon
carbonDf <- successionLog %>% select(Time, SOMTC, C_SOM1surf, C_SOM1soil, C_SOM2, C_SOM3) %>% 
  pivot_longer(cols = "SOMTC":"C_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(carbonDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("SOMTC" = "red", "C_SOM1surf" = "cornflowerblue", "C_SOM1soil" = "darkorchid", "C_SOM2" = "darkorange", "C_SOM3" = "darkgreen"))

# Nitrogen
nitrogenDf <- successionLog %>% select(Time, TotalSoilN, N_SOM1surf, N_SOM1soil, N_SOM2, N_SOM3) %>% 
  pivot_longer(cols = "TotalSoilN":"N_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(nitrogenDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("TotalSoilN" = "red", "N_SOM1surf" = "cornflowerblue", "N_SOM1soil" = "darkorchid", "N_SOM2" = "darkorange", "N_SOM3" = "darkgreen"))

# Ratio
ratioDf <- rbind(carbonDf, nitrogenDf) %>%
  pivot_wider(names_from = "Pool", values_from = "g_m2") %>%
  mutate(Total = SOMTC / TotalSoilN,
         Surf = C_SOM1surf / N_SOM1surf,
         Soil = C_SOM1soil / N_SOM1soil,
         SOM2 = C_SOM2 / N_SOM2,
         SOM3 = C_SOM3 / N_SOM3) %>%
  select(Time, Total, Surf, Soil, SOM2, SOM3) %>%
  pivot_longer(cols = "Total":"SOM3", names_to = "Pool", values_to = "C:N Ratio")

ggplot(ratioDf, aes(x = Time, y = `C:N Ratio`, col = Pool)) +
  geom_line(size  = 1) +
  theme_classic() +
  ylim(0,80) +
  annotate("text", x = 31, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  # geom_hline(yintercept = 5, linetype = "dashed", col = "blue") +
  geom_hline(yintercept = 40, linetype = "dashed") +
  scale_color_manual(values = c("Total" = "red", "Surf" = "cornflowerblue", "Soil" = "darkorchid", "SOM2" = "darkorange", "SOM3" = "darkgreen"))

```

## Test 2

```{r}
successionLog <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Soil Grid Data/Soil Testing/Single Cell/Test 2/NECN-succession-log.csv")

# Carbon
carbonDf <- successionLog %>% select(Time, SOMTC, C_SOM1surf, C_SOM1soil, C_SOM2, C_SOM3) %>% 
  pivot_longer(cols = "SOMTC":"C_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(carbonDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.2\nDecaySoil = 1.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("SOMTC" = "red", "C_SOM1surf" = "cornflowerblue", "C_SOM1soil" = "darkorchid", "C_SOM2" = "darkorange", "C_SOM3" = "darkgreen"))

# Nitrogen
nitrogenDf <- successionLog %>% select(Time, TotalSoilN, N_SOM1surf, N_SOM1soil, N_SOM2, N_SOM3) %>% 
  pivot_longer(cols = "TotalSoilN":"N_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(nitrogenDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.2\nDecaySoil = 1.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("TotalSoilN" = "red", "N_SOM1surf" = "cornflowerblue", "N_SOM1soil" = "darkorchid", "N_SOM2" = "darkorange", "N_SOM3" = "darkgreen"))

# Ratio
ratioDf <- rbind(carbonDf, nitrogenDf) %>%
  pivot_wider(names_from = "Pool", values_from = "g_m2") %>%
  mutate(Total = SOMTC / TotalSoilN,
         Surf = C_SOM1surf / N_SOM1surf,
         Soil = C_SOM1soil / N_SOM1soil,
         SOM2 = C_SOM2 / N_SOM2,
         SOM3 = C_SOM3 / N_SOM3) %>%
  select(Time, Total, Surf, Soil, SOM2, SOM3) %>%
  pivot_longer(cols = "Total":"SOM3", names_to = "Pool", values_to = "C:N Ratio")

ggplot(ratioDf, aes(x = Time, y = `C:N Ratio`, col = Pool)) +
  geom_line(size  = 1) +
  theme_classic() +
  ylim(0,80) +
  annotate("text", x = 31, y = Inf, label = "DecaySurf = 1.2\nDecaySoil = 1.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  # geom_hline(yintercept = 5, linetype = "dashed", col = "blue") +
  geom_hline(yintercept = 40, linetype = "dashed") +
  scale_color_manual(values = c("Total" = "red", "Surf" = "cornflowerblue", "Soil" = "darkorchid", "SOM2" = "darkorange", "SOM3" = "darkgreen"))

```


# 5000 Ha

## Test 1

```{r}
successionLog <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Soil Grid Data/Soil Testing/Five Thousand HA/Test 1/NECN-succession-log.csv")

# Carbon
carbonDf <- successionLog %>% select(Time, SOMTC, C_SOM1surf, C_SOM1soil, C_SOM2, C_SOM3) %>% 
  pivot_longer(cols = "SOMTC":"C_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(carbonDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("SOMTC" = "red", "C_SOM1surf" = "cornflowerblue", "C_SOM1soil" = "darkorchid", "C_SOM2" = "darkorange", "C_SOM3" = "darkgreen"))

# Nitrogen
nitrogenDf <- successionLog %>% select(Time, TotalSoilN, N_SOM1surf, N_SOM1soil, N_SOM2, N_SOM3) %>% 
  pivot_longer(cols = "TotalSoilN":"N_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(nitrogenDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("TotalSoilN" = "red", "N_SOM1surf" = "cornflowerblue", "N_SOM1soil" = "darkorchid", "N_SOM2" = "darkorange", "N_SOM3" = "darkgreen"))

# Ratio
ratioDf <- rbind(carbonDf, nitrogenDf) %>%
  pivot_wider(names_from = "Pool", values_from = "g_m2") %>%
  mutate(Total = SOMTC / TotalSoilN,
         Surf = C_SOM1surf / N_SOM1surf,
         Soil = C_SOM1soil / N_SOM1soil,
         SOM2 = C_SOM2 / N_SOM2,
         SOM3 = C_SOM3 / N_SOM3) %>%
  select(Time, Total, Surf, Soil, SOM2, SOM3) %>%
  pivot_longer(cols = "Total":"SOM3", names_to = "Pool", values_to = "C:N Ratio")

ggplot(ratioDf, aes(x = Time, y = `C:N Ratio`, col = Pool)) +
  geom_line(size  = 1) +
  theme_classic() +
  ylim(0,80) +
  annotate("text", x = 31, y = Inf, label = "DecaySurf = 1.5\nDecaySoil = 2.5\nDecaySOM2 = 0.5\nDecaySOM3 = 0.0000001\nDenitrification = 0.05\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  # geom_hline(yintercept = 5, linetype = "dashed", col = "blue") +
  geom_hline(yintercept = 40, linetype = "dashed") +
  scale_color_manual(values = c("Total" = "red", "Surf" = "cornflowerblue", "Soil" = "darkorchid", "SOM2" = "darkorange", "SOM3" = "darkgreen"))

```

## Test 2

```{r}
successionLog <- read_csv("C:/Users/lagoodal/Desktop/Dissertation Stuff/Chapter 3/Soil Grid Data/Soil Testing/Five Thousand HA/Test 2/NECN-succession-log.csv")

# Carbon
carbonDf <- successionLog %>% select(Time, SOMTC, C_SOM1surf, C_SOM1soil, C_SOM2, C_SOM3) %>% 
  pivot_longer(cols = "SOMTC":"C_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(carbonDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 0.5\nDecaySoil = 0.3\nDecaySOM2 = 0.2\nDecaySOM3 = 0.0000001\nDenitrification = 0.07\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("SOMTC" = "red", "C_SOM1surf" = "cornflowerblue", "C_SOM1soil" = "darkorchid", "C_SOM2" = "darkorange", "C_SOM3" = "darkgreen"))

# Nitrogen
nitrogenDf <- successionLog %>% select(Time, TotalSoilN, N_SOM1surf, N_SOM1soil, N_SOM2, N_SOM3) %>% 
  pivot_longer(cols = "TotalSoilN":"N_SOM3", names_to = "Pool", values_to = "g_m2")
ggplot(nitrogenDf, aes(x = Time, y = g_m2, col = Pool)) +
  geom_line(size = 1) +
  theme_classic() +
  annotate("text", x = 27, y = Inf, label = "DecaySurf = 0.5\nDecaySoil = 0.3\nDecaySOM2 = 0.2\nDecaySOM3 = 0.0000001\nDenitrification = 0.07\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  scale_color_manual(values = c("TotalSoilN" = "red", "N_SOM1surf" = "cornflowerblue", "N_SOM1soil" = "darkorchid", "N_SOM2" = "darkorange", "N_SOM3" = "darkgreen"))

# Ratio
ratioDf <- rbind(carbonDf, nitrogenDf) %>%
  pivot_wider(names_from = "Pool", values_from = "g_m2") %>%
  mutate(Total = SOMTC / TotalSoilN,
         Surf = C_SOM1surf / N_SOM1surf,
         Soil = C_SOM1soil / N_SOM1soil,
         SOM2 = C_SOM2 / N_SOM2,
         SOM3 = C_SOM3 / N_SOM3) %>%
  select(Time, Total, Surf, Soil, SOM2, SOM3) %>%
  pivot_longer(cols = "Total":"SOM3", names_to = "Pool", values_to = "C:N Ratio")

ggplot(ratioDf, aes(x = Time, y = `C:N Ratio`, col = Pool)) +
  geom_line(size  = 1) +
  theme_classic() +
  ylim(0,100) +
  annotate("text", x = 31, y = Inf, label = "DecaySurf = 0.5\nDecaySoil = 0.3\nDecaySOM2 = 0.2\nDecaySOM3 = 0.0000001\nDenitrification = 0.07\nNSlope = 0.05\nNIntercept = 0.3", 
           hjust = 1, vjust = 1, size = 3, color = "black", 
           fontface = "bold", family = "serif") +
  theme(plot.margin = margin(10, 40, 10, 10)) +
  scale_x_continuous(breaks = seq(0, 100, 10), limits = c(0,100)) +
  # geom_hline(yintercept = 5, linetype = "dashed", col = "blue") +
  geom_hline(yintercept = 40, linetype = "dashed") +
  scale_color_manual(values = c("Total" = "red", "Surf" = "cornflowerblue", "Soil" = "darkorchid", "SOM2" = "darkorange", "SOM3" = "darkgreen"))

```


